### ISSUE TITLE
bounding box coordinates

### ISSUE THREAD

**Issue by lazrak-mouad** [hasanirtiza/Pedestron#10]
I'm so gratefull for the work you have done and all the effort you put on this project, but I still have a little issue : 
The issue is that I wanna evaluate the result of Pedestron on my own dataset  (inference evaluation) using the mAP metric and for this I need the bounding boxes coordinates, is there a way to get them ?

Thank you in advance.

**Comment by hasanirtiza** [comment]
Of course you can get bounding-box coordinates. The easiest way is to have a look at `tools/demo.py` and you can see how the bounding boxes are drawn on the demo images using [show_result()](https://github.com/hasanirtiza/Pedestron/blob/master/mmdet/apis/inference.py). 
Alternatively, have a look at `tools/test_city_person.py` from lines `202-215` and see how you can iterate over all bounding-boxes of the dataset.
