### ISSUE TITLE
Pedestron on google-colab: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'

### ISSUE THREAD

**Issue by housong1996** [hasanirtiza/Pedestron#101]
Hi~
when i run Pedestron code on google-colab: 
`%%shell`
`cd /content/drive/MyDrive/open-mmlab/Pedestron/
python tools/train.py configs/elephant/cityperson/cascade_hrnet.py
`
I got an error :
`RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'`

So i would like know the reason and how to debug it.
![image](https://user-images.githubusercontent.com/61791124/125088966-83a7e480-e100-11eb-9575-5a9f92a4364c.png)

**Comment by hasanirtiza** [comment]
Modify lines, as per instructed [here](https://github.com/hasanirtiza/Pedestron/issues/17#issuecomment-660964646).

**Comment by housong1996** [comment]
Thanks for your help~
