### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by cjz1259965881** [hasanirtiza/Pedestron#102]
ubuntu 18.04
python 3.7
pytorch 1.9.0
gcc 7.3/8.2/9.4
cuda 11.1

Has anyone successfully installed  Pedestron on cuda 11.1? 
Part of error message i got is as below：

`running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.nms.soft_nms_cpu' extension
Emitting ninja build file /home/zcj/code/open-mmlab/Pedestron/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /home/zcj/anaconda3/envs/open-mmlab/compiler_compat -L/home/zcj/anaconda3/envs/open-mmlab/lib -Wl,-rpath=/home/zcj/anaconda3/envs/open-mmlab/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/zcj/code/open-mmlab/Pedestron/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.7/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so
building 'mmdet.ops.roi_align.roi_align_cuda' extension
Emitting ninja build file /home/zcj/code/open-mmlab/Pedestron/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /home/zcj/code/open-mmlab/Pedestron/build/temp.linux-x86_64-3.7/mmdet/ops/roi_align/src/roi_align_cuda.o.d -pthread -B /home/zcj/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zcj/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/zcj/code/open-mmlab/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp -o /home/zcj/code/open-mmlab/Pedestron/build/temp.linux-x86_64-3.7/mmdet/ops/roi_align/src/roi_align_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/zcj/code/open-mmlab/Pedestron/build/temp.linux-x86_64-3.7/mmdet/ops/roi_align/src/roi_align_cuda.o 
c++ -MMD -MF /home/zcj/code/open-mmlab/Pedestron/build/temp.linux-x86_64-3.7/mmdet/ops/roi_align/src/roi_align_cuda.o.d -pthread -B /home/zcj/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zcj/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/zcj/code/open-mmlab/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp -o /home/zcj/code/open-mmlab/Pedestron/build/temp.linux-x86_64-3.7/mmdet/ops/roi_align/src/roi_align_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/zcj/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140:0,`

Is it caused by CUDA version too high？

**Comment by hasanirtiza** [comment]
> ubuntu 18.04
> python 3.7
> pytorch 1.9.0
> gcc 7.3/8.2/9.4
> cuda 11.1
> 
> Has anyone successfully installed Pedestron on cuda 11.1?

Yes, a lot of times. Your CUDA version seems fine, your PyTorch version seems too high. I would recommend you to have a look at the [installation](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) file, to understand which versions of PyTorch, mmcv etc. are compatible.

**Comment by cjz1259965881** [comment]
> > ubuntu 18.04
> > python 3.7
> > pytorch 1.9.0
> > gcc 7.3/8.2/9.4
> > cuda 11.1
> > Has anyone successfully installed Pedestron on cuda 11.1?
> 
> Yes, a lot of times. Your CUDA version seems fine, your PyTorch version seems too high. I would recommend you to have a look at the [installation](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) file, to understand which versions of PyTorch, mmcv etc. are compatible.

ok. I  got it. thank you !

**Comment by DongDem** [comment]
hi @cjz1259965881. You can follow my PR (https://github.com/hasanirtiza/Pedestron/pull/109) to easier install environment
