### ISSUE TITLE
Permission denied on google drive

### ISSUE THREAD

**Issue by InukKang** [hasanirtiza/Pedestron#104]
Following your google colab demo, there is permission denial on google drive.
![image](https://user-images.githubusercontent.com/69806620/128227119-414c1666-e578-4e45-9347-040823ab4838.png)

And it shows 404 Error. How it can be fixed??
![image](https://user-images.githubusercontent.com/69806620/128228672-6d22528b-43a9-4dc6-8965-99cd7cbd2708.png)

**Comment by hasanirtiza** [comment]
You can download this [pre trained model instead](https://drive.google.com/file/d/1Nsvf7qU02fvRdTO2jcKo5Rgr5JOV3Ptx/view).
