### ISSUE TITLE
Requesting 'gt-Scale=medium.mat' or a method to generate the same for Caltech

### ISSUE THREAD

**Issue by AbhishekGagneja** [hasanirtiza/Pedestron#106]
Hello. Dr. Hasan
Congratulations on the wonderful work you have done with this repo and this paper.
I have a request. Is it possible to share the 'gt-<subset>.mat' files for all subsets or a code to generate the same for Caltech. 
I am trying to solve a problem that needs evaluation on particularly small and medium sized visible annotations and I am stuck without these gt files.
Can you please help ?
Regards

**Comment by hasanirtiza** [comment]
Abishek, I think you can generate all the files from this repo. Did you have a look at [eval_caltech](https://github.com/hasanirtiza/Pedestron/tree/master/tools/caltech/eval_caltech) folder ? Please refer to #5 and see my comment on generating all gt files. In short, inside `db_eval.m` you can see all settings on lines 32-51, you can change on line 75 and set `exps = exps(5)` for  `gt-Scale=medium`, it will evaluate and also will create the gt file.

**Comment by AbhishekGagneja** [comment]
thank you so much sir.. thank you for the prompt reply.. you saved me !!!
