### ISSUE TITLE
Pre-trained model for Wider Pedestrian

### ISSUE THREAD

**Issue by daooshee** [hasanirtiza/Pedestron#107]
Thanks for your great work! I want to train models for my own datasets based on general human/person detection pre-training. However, I can only find the model of CrowdHuman in [README.md](https://github.com/hasanirtiza/Pedestron/blob/master/README.md). Could you please provide the pre-trained model of Wider Pedestrian? Thank you!

**Comment by hasanirtiza** [comment]
We will try to upload the `wider pedestrian` model, it might take 3,4 days.

**Comment by daooshee** [comment]
Thank you so much!
