### ISSUE TITLE
Requesting best trained models for RetinaNet and FasterRCNN with ResNet-50 backbone

### ISSUE THREAD

**Issue by AbhishekGagneja** [hasanirtiza/Pedestron#108]
Dear Dr. Irtiza
This is truly a wonderful repository and has made the life of researchers, like me, who are working on Pedestrian detection much more streamlined. 
The trouble I have been facing is with the unavailability of your best performing pre-trained weights. I am currently in need of the RetinaNet and FRCNN models with ResNet-50 backbone. I would request you to kindly suggest a way for me to get these since the links inavailable in the ModelZoo dont seem to work.
Looking forward to your reply.
Regards
Abhishek

**Comment by hasanirtiza** [comment]
Abishek, the issue is, that I have no longer access to the models and unfortunately they are seem to be lost. What I can tell you is that, we adopted progressive fine tuning for the above mentioned models, to reach the mentioned accuracy.

**Comment by AbhishekGagneja** [comment]
Thank you for your reply sir. I unfortunately find myself with lack of enough computational resources to execute the same set of experiments as you have so I am currently not able to reproduce your results. Will try to manage with what I have. Thank you for your promptness and continued support. This is a landmark repo in the area indeed. 
Closing the issue.

**Comment by hasanirtiza** [comment]
So may be there is a way, this is the [link to a folder](https://drive.google.com/drive/folders/12m7UASqsMaN-lyaseoJ1AvhOTTZQH8kr?usp=sharing) where you will see around 14 models. Most probably, there is a model for retinanet (with ResNext) and Faster RCNN (with HRNET). You need to find them by passing the each model and matching the accuracy with Table on readme.md.

There is quick way of doing it, simply rename the models from epoch_1.pth.stu to epoch_14.pth.stu and run this command:

`python ./tools/test_city_person.py configs/elephant/cityperson/ga_retinanet_ResNeXt101.py ./all_models/epoch_ 1 14\
 --out result_citypersons.json --mean_teacher`

You can do this also for Faster RCNN. Hope that helps.

**Comment by AbhishekGagneja** [comment]
I'll give it a try.. thank you
