### ISSUE TITLE
ImportError: cannot import name 'get_dist_info' from 'mmcv.runner.utils'

### ISSUE THREAD

**Issue by Varat7v2** [hasanirtiza/Pedestron#11]
When I run this command:
`python tools/demo.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_5.pth.stu demo/ result_demo/ `

I am getting this error:
`ImportError: cannot import name 'get_dist_info' from 'mmcv.runner.utils'`

I have installed mmdetection as per your [instructions](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) and also tried for [conda-instruction](https://gist.github.com/hellock/bf23cd7348c727d69d48682cb6909047).

I updated **mmcv** as per the suggestions got online but nothing is working. Now my mmcv version is 0.4.4

**Comment by Varat7v2** [comment]
I solved this issue by downgrading mmcv from 0.4.4 to 0.2.14 and the demo.py is running fine but there are no any bounding boxes on the result images.

**Comment by hasanirtiza** [comment]
Which configuration file and pre-trained model did you use for the demo?

**Comment by Varat7v2** [comment]
I am using the following configuration file and the pre-trained model:
> configs/elephant/cityperson/cascade_hrnet.py 
> epoch_7.pth.stu
> test images as provided in the demo folder

**Comment by hasanirtiza** [comment]
How are you running `epoch_7.pth.stu` with the configuration of cascade_hrnet.py ? It seems to me that `epoch_7.pth.stu` is a  pre-trained model for RetinaNet, not for the Cascade Mask R-CNN. Or did you train your own model ?

**Comment by Varat7v2** [comment]
Oh yeah! I did not notice that. I changed the config file with that of Retinanet and now its working. Thank you very much. If I want to run this model with SSD300 or RetinaNet on mobile devices or Jetson, will it run efficiently in regard of inference time? Now I am thinking of trying it on Jetson.

Also I was earlier trying running it on my PC without GPU but it was showing some cuda error: `ImportError: cannot import name 'deform_conv_cuda'` Won't it run only on CPU?

Thank you again.

**Comment by hasanirtiza** [comment]
As of now Pedestron does not support a CPU-only version. #7

**Comment by Varat7v2** [comment]
Okay thanks.

**Comment by zhulishun** [comment]
> I solved this issue by downgrading mmcv from 0.4.4 to 0.2.14 and the demo.py is running fine but there are no any bounding boxes on the result images.

Hi~How to downgrading mmcv from 0.4.4 to 0.2.14 ?

**Comment by Varat7v2** [comment]
@zhulishun you can downgrade it with `pip install mmcv==0.2.14`

**Comment by zhulishun** [comment]
> @zhulishun you can downgrade it with `pip install mmcv==0.2.14`
thank u! I try, but
Pedestron$ pip install mmcv==0.2.14
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fef88377c50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/mmcv/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fef88377be0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/mmcv/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fef883774e0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/mmcv/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fef88377390>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/mmcv/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fef88377240>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/mmcv/
ERROR: Could not find a version that satisfies the requirement mmcv==0.2.14 (from versions: none)
ERROR: No matching distribution found for mmcv==0.2.14

**Comment by hasanirtiza** [comment]
There seems to be a problem in your pip installation. This command should work 
`pip install mmcv==0.2.14`
 or 
`pip3 install mmcv==0.2.14`
Depending upon your system. From the error log, it appears to me that you have some issues in your pip installation, have a look [here](https://github.com/pypa/pip/issues/4439) or [here](https://github.com/pypa/pip/issues/5362).

**Comment by AdityaSrivastava1234** [comment]
Hi, I'm also facing the same issue while trying to do fine-tuning with cascade mask rcnn --> "ImportError: cannot import name 'get_dist_info' from 'mmcv.runner.utils' ". I'm following the colab notebook given by the authors which installs mmcv using the command --> "pip install mmcv==0.2.14". Still the problem persists. Please help me out, thanks in advance!

**Comment by hasanirtiza** [comment]
Most probably it is still an installation issue, after installing mmcv did you compile Pedestron using the following command ?
`python setup.py develop`

Secondly, juts have a look at the [installation page](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) and see if you have followed all the instructions correctly.
