### ISSUE TITLE
model path not accessible

### ISSUE THREAD

**Issue by aktaksh** [hasanirtiza/Pedestron#110]
https://drive.google.com/uc?id=1B487ljaU9FxTSFaLoirOSqadZ-39QEH8 -O CascadeRCNNCP_model.pth.stu 
Can you share the drive or place the model in repo here itself. This is stopping us from free execution

**Comment by hasanirtiza** [comment]
You can download model from the table in [read me](https://drive.google.com/file/d/12mWjmWBv-4wra8hCNF71Wq0U2va0Ai8e/view).
