### ISSUE TITLE
Classes for the CityPersons dataset

### ISSUE THREAD

**Issue by supremePSS** [hasanirtiza/Pedestron#112]
Hi, i have met some problems about the CityPersons dataset. There are 5 classes in the CityPersons, i.e. 'pedestrians', 'riders', 'sitting persons', 'other persons with unusual postures',  and 'group of people'. I want to know  whether your models were trained to predict the 5 class respectively,  or just see all the objects  as one class. I find your code in test_city_person.py writes all the predicted box as 'category_id'=1,   shown as following:
![1632915116(1)](https://user-images.githubusercontent.com/52562191/135260509-4b95d988-bddb-48d9-881e-21634c6b8250.png)
It seems like you see all the objects as one calss, is that right?
thanks a lot!

**Comment by hasanirtiza** [comment]
No, that is not right, the code only treats `pedestrians` as valid samples as per the evaluation protocol. So during training, only ones with pedestrian class are used. The evaluation protocol in pedestrian detection literature(cityperson, ecp etc.), only considers `pedestrians`, all other classes are ignored.
