### ISSUE TITLE
Can PEDESTRON detect video files?

### ISSUE THREAD

**Issue by Philharmy-Wang** [hasanirtiza/Pedestron#114]
I would like to perform inspection of video files. 
Can Pedestron detect video files or camera videos in real time?

Thank you very much!

**Comment by hasanirtiza** [comment]
It should also work on video files, you simply need to add a video reader in the demo script, grab a frame and pass it to the `inference_detector`. Have a look at this [video_demo.py](https://github.com/open-mmlab/mmdetection/blob/master/demo/video_demo.py) to understand how to do it.
