### ISSUE TITLE
Can official ECP annotations be supported instead of the unofficial annotations provided in this project ?

### ISSUE THREAD

**Issue by AndyVerne** [hasanirtiza/Pedestron#118]
First, thanks for the great job.
I want to know if the official annotations of EuroCity Persons are supported in this project. 
If not, could you tell me how to deal with the official ECP annotations format to be used in this project ? 
Thanks in advance.  ; )

**Comment by hasanirtiza** [comment]
I am not sure if I understand you correctly. Pedestron expects annotations in the COCO format. Else you can write your own custom dataset, in `mmdet/datasets`, we do a custom dataset for CSP (coco_csp_ori). Secondly, we provide script to convert ECP annotations into the COCO format. Did you have a look [here](https://github.com/hasanirtiza/Pedestron/blob/master/tools/convert_datasets/eurocity/convert_eurocity_to_coco.py). Basically you work with official annotations, simply convert them into COCO format.

**Comment by AndyVerne** [comment]
> I am not sure if I understand you correctly. Pedestron expects annotations in the COCO format. Else you can write your own custom dataset, in `mmdet/datasets`, we do a custom dataset for CSP (coco_csp_ori). Secondly, we provide script to convert ECP annotations into the COCO format. Did you have a look [here](https://github.com/hasanirtiza/Pedestron/blob/master/tools/convert_datasets/eurocity/convert_eurocity_to_coco.py). Basically you work with official annotations, simply convert them into COCO format.

Wow! That's great!
Sorry about my unclear expression.  Things you say is what I try to express. 
Thanks a lot. And I really appreciate your work!
