### ISSUE TITLE
Can Pedestron run on Windows?

### ISSUE THREAD

**Issue by dogdogpee** [hasanirtiza/Pedestron#119]
Hi,

Thanks for such a nice work!

I am wondering if it is possible to install and run these detectors on Windows because Linux is required as written Installation?

**Comment by hasanirtiza** [comment]
Never tried, cant say. This is an old version of `mmdetection`. Check on [mmdetection](https://github.com/open-mmlab/mmdetection) page if you can compile it on windows.
