### ISSUE TITLE
Deadlink for the pretrained model parameters

### ISSUE THREAD

**Issue by dandax123** [hasanirtiza/Pedestron#124]
Good day,

The Google colab version is supposed to extract pretrained model paramers from this link below.
https://drive.google.com/uc?id=1B487ljaU9FxTSFaLoirOSqadZ-39QEH8 
Currently, the link is dead. 

Can you please provide a new link ?

**Comment by hasanirtiza** [comment]
I am not sure which model exactly are you referring to, I guess you are already aware that the benchmarked models can be downloaded through the readme.md table. If you are referring to basic imagenet/coco pretrained model provided by mmdetection, have a look at #111.

**Comment by dandax123** [comment]
Okay, I understand better now. Although , I was referring to the link in the Google collab file (that was supposed to download a pretrained model with gdown).

**Comment by hasanirtiza** [comment]
The links are broken, since,  the models are shifted to a new gdrive. We will adjust it hopefully in sometime in future. You can download [this](https://drive.google.com/file/d/12mWjmWBv-4wra8hCNF71Wq0U2va0Ai8e/view) model instead.
