### ISSUE TITLE
Gdown doesn't download the model parameters

### ISSUE THREAD

**Issue by dandax123** [hasanirtiza/Pedestron#125]
Good day, 

Thanks for your help in #124 issue.  I was finally able to run inference on an image.
 The main issue that I discovered was the the gdown doesn't download the model. It only downloads the HTML page, instead of model parameters.

**Comment by hasanirtiza** [comment]
As said in the previous issue, the links are broken in the colab, one needs to redirect it to correct links. PR are welcome. Otherwise, we will do it at some point in future.
