### ISSUE TITLE
How i can make predictions on my own dataset ?

### ISSUE THREAD

**Issue by yassiney** [hasanirtiza/Pedestron#127]
Hello, hope you are doing well, I commented to you here to ask for your help, please.
Show me how to test your pre-trained model on my own data?
Thank you in advance.

**Comment by hasanirtiza** [comment]
You need to do two steps:

1) Download the pre-trained model from the links given in `README.MD`, for example [this model](https://drive.google.com/file/d/1Nsvf7qU02fvRdTO2jcKo5Rgr5JOV3Ptx/view). Create a folder called `models_pretrained`, copy the model in this folder.

2) Then simply, put your images (folder you will create) in the folder called `demo` inside this repo, run the command below command (provided you have installed Pedestron correctly). The resultant images will be stored in folder `result_demo`.

```shell
python tools/demo.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_19.pth.stu demo/ result_demo/ 
```

That should be it.

**Comment by yassiney** [comment]
Thank you very much

Le jeu. 13 janv. 2022 à 18:07, Irtiza Hasan ***@***.***> a
écrit :

**Comment by yassiney** [comment]
Hello, @hasanirtiza 
I used your suggestion but i didn't get bounding box coordinates to test your pre-trained model on my own data (calculate average precision, recall and precision )
Thank you in advance.
