### ISSUE TITLE
Here's how to support cuda11/pytorch-1.10

### ISSUE THREAD

**Issue by ajtao** [hasanirtiza/Pedestron#131]
I have an Ampere-class GPU and so i needed to get this code working with cuda-11.
I think a lot of people might benefit from this, so i'll just share it here

Here are the steps:

conda create -n pedestron python=3.8 anaconda
conda activate pedestron
pip install mmcv==0.2.10
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch -y

# not sure these are needed ...
pip install cython
pip install numpy
pip install instaboostfast
pip install git+https://github.com/cocodataset/panopticapi.git
pip install git+https://github.com/lvis-dataset/lvis-api.git
pip install albumentations>=0.3.2 --no-binary imgaug,albumentations         
pip install terminaltables

# modify Pedestron code to change all AT_CHECK to TORCH_CHECK
python setup.py develop

After this i was able to run demo.py successfully.

**Comment by hasanirtiza** [comment]
This is cool, could you also confirm if you can train using the same environment. I will add this to the installation file then.
