### ISSUE TITLE
When I run “python tools/train.py configs/elephant/cityperson/cascade_hrnet.py”，report "TypeError: CascadeRCNN: __init__() got an unexpected keyword argument 'num_stages'"

### ISSUE THREAD

**Issue by KyleLee233** [hasanirtiza/Pedestron#135]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/elephant/cityperson/cascade_hrnet.py

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?

**Environment**
 - OS: windows 10
 - PyTorch version 1.10.1
- How you installed PyTorch source
- GPU model rtx3060
- CUDA and CUDNN version 11.3 8200

**Comment by hasanirtiza** [comment]
Most probably you have installed the wrong version of `mmdetection` and/or `mmcv`. Confirm your versions of mmcv and mmdet and have quick look at this [issue](https://github.com/DevashishPrasad/CascadeTabNet/issues/132).

**Comment by KyleLee233** [comment]
> Most probably you have installed the wrong version of `mmdetection` and/or `mmcv`. Confirm your versions of mmcv and mmdet and have quick look at this [issue](https://github.com/DevashishPrasad/CascadeTabNet/issues/132).

My mmcv version is 1.4.7 and mmdet version is 2.22.0;which version of mmcv and mmdet shoud I use ?
I read the issue you mentioned above  and tried changing the config file but report  another error。

**Comment by hasanirtiza** [comment]
Look at the [installation file](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) for the versions for Pedestron. Your mmcv version is too high.

**Comment by KyleLee233** [comment]
> Look at the [installation file](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) for the ver

> Look at the [installation file](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) for the versions for Pedestron. Your mmcv version is too high.

the installation file doesn't mention the version of mmdet;I installed mmdet as the installation file mentioned but still get the 2.22.0  version of mmdet. so I feel a bit confused.

**Comment by hasanirtiza** [comment]
You should install mmdet through this repo, look at the installation file on how to [install Pedestron](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md). Try not to install it through `pip`.
