### ISSUE TITLE
Running Inference on Custom Dataset in CoCo-Format

### ISSUE THREAD

**Issue by fritzeinhorn** [hasanirtiza/Pedestron#136]
Hello, 
I find your Project really impressive and am trying to run an inference on my own Dataset that is annotated in CoCo Format. So far I've tried to paste my images into the **_demo/_** folder and the model is working fine, showing me the outputs in the **_result_demo/_** folder. I am using the colab version. However i am trying to find out how I can get the bounding box coordinates (with corresponding confidence if possible) as an output file in whichever format to run further analysis. 

I greatly appreciate your help!

**Comment by fritzeinhorn** [comment]
As an addition, is it possible to run the inference on only part of the images without cropping them all? In this case there is a sports video with spectators where the inference should only detect Humans in a specific defined area (e.g. the Court).

**Comment by hasanirtiza** [comment]
> Hello, I find your Project really impressive and am trying to run an inference on my own Dataset that is annotated in CoCo Format. So far I've tried to paste my images into the **_demo/_** folder and the model is working fine, showing me the outputs in the **_result_demo/_** folder. I am using the colab version. However i am trying to find out how I can get the bounding box coordinates (with corresponding confidence if possible) as an output file in whichever format to run further analysis.
> 
> I greatly appreciate your help!

I think if you go to `tools/demo.py` and on line 37 you get `results = inference_detector(model, image)`, this should contain bounding boxes. You can save them in whatever format you want.

**Comment by hasanirtiza** [comment]
> As an addition, is it possible to run the inference on only part of the images without cropping them all? In this case there is a sports video with spectators where the inference should only detect Humans in a specific defined area (e.g. the Court).

Perhaps an easy (not necessarily the smartest) way is to simply check coordinate of each individual bbox and and based on the location determine whether to keep it or not,
