### ISSUE TITLE
How did you compute the Log average miss rate value.

### ISSUE THREAD

**Issue by ajay1234567899** [hasanirtiza/Pedestron#141]
Hello sir,
I wanted to know how you computed the log averaged miss rate value.
Did you write scripts of your own or did MM detection provide a tool?

**Comment by hasanirtiza** [comment]
We computed LAMR by using the official scripts provided by the benchmark publishers. For example have a look at [CItyPerson](https://github.com/hasanirtiza/Pedestron/tree/master/tools/cityPerson). You can have a look at [test_city_person.py](https://github.com/hasanirtiza/Pedestron/blob/master/tools/test_city_person.py) and [test_euroCity.py](https://github.com/hasanirtiza/Pedestron/blob/master/tools/test_euroCity.py) on how to call them. Additionally, there was also a [PR request](https://github.com/hasanirtiza/Pedestron/pull/77) which modified the original mmdetection evaluation code.

**Comment by ajay1234567899** [comment]
Hello sir,

I could generate results for city persons using the scripts you mentioned.

But for the Caltech dataset, I cannot find the scripts that compute the LAMR.
It would be great if you could point me to the same.

Thank you
