### ISSUE TITLE
LAMR for the caltech dataset

### ISSUE THREAD

**Issue by ajay1234567899** [hasanirtiza/Pedestron#142]
Hello sir,

I could generate results for city persons using the scripts you mentioned.

But for the Caltech dataset, I cannot find the scripts that compute the LAMR.
It would be great if you could point me to the same.

Thank you

_Originally posted by @ajay1234567899 in https://github.com/hasanirtiza/Pedestron/issues/141#issuecomment-1185208895_

**Comment by hasanirtiza** [comment]
Please refer to [Datasets-PreProcessing.md](https://github.com/hasanirtiza/Pedestron/blob/master/Datasets-PreProcessing.md) file, scroll down and see under the heading **caltech** on how to evaluate.
