### ISSUE TITLE
where to find the annotations for the extra train data of citypersons dataset?

### ISSUE THREAD

**Issue by ajay1234567899** [hasanirtiza/Pedestron#143]
Hello sir,
Your repo mentioned that you had achieved state-of-the-art on the city person dataset by training on the extra train data, around 19k images.

I am not able to find the ground truth annotations of the same.
Please do point out the location of the extra annotations.

Also, to get the state-of-the-art results of 7.5 MR-2 on the city persons you had used a training strategy, I cannot get the strategy properly. Please do point me to your pre-print version, which had its details
Your current version on arxiv does not have sections 6.1 and 6.2

**Comment by hasanirtiza** [comment]
Please refer to our [Arxiv paper](https://openaccess.thecvf.com/content/CVPR2021/papers/Hasan_Generalizable_Pedestrian_Detection_The_Elephant_in_the_Room_CVPR_2021_paper.pdf), it includes all the detail on which data we used to pre-train and progressively finetune. In particular, have a look at section 7.1 to see how we obtain 7.5 MR-2 on citypersons.
