### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'frozen_stages'

### ISSUE THREAD

**Issue by ajay1234567899** [hasanirtiza/Pedestron#144]
Hello sir,

I wanted to fine-tune the model with a new dataset.
I don't want to change the weights of the backbone so I had set the frozen_stages =3 

but when I run the train script I am getting this error.

**TypeError: __init__() got an unexpected keyword argument 'frozen_stages'**

config file used is : https://github.com/hasanirtiza/Pedestron/blob/master/configs/elephant/cityperson/cascade_hrnet.py

please help me with this issue.
Thank you

**Comment by hasanirtiza** [comment]
I think the main issue is that Pedestron is built on older version. You need to a bit of search on mmdetcetion issues, [such as this one](https://github.com/open-mmlab/mmdetection/issues/1377).
