### ISSUE TITLE
 Identifier "THCudaCheck" is undefined

### ISSUE THREAD

**Issue by Simardeep27** [hasanirtiza/Pedestron#148]
Hi,

I am trying to run the setup.py file but during the build process of "roi_align_kernel.cu", 
I receive an error:
**\src\roi_align_kernel.cu(147): error: identifier "THCudaCheck" is undefined**

**Environment**
 - OS: Windows 11
 - GCC: 8.3
 - PyTorch version: 1.11.0
- CUDA: 11.3

Is there any method to resolve this issue?

**Comment by hasanirtiza** [comment]
Did you follow the instructions in [installation file](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) ?
