### ISSUE TITLE
Hello, are you using Casecade RCNN training network or Casecade mask RCNN?

### ISSUE THREAD

**Issue by playyalp1** [hasanirtiza/Pedestron#15]
Hello, are you using Casecade RCNN training network or Casecade mask RCNN?

**Comment by hasanirtiza** [comment]
We provide a list of detectors, including cascade with or without mask. Currently, most of the pre-trained models that we provide are based on Cascade Mask R-CNN. However, the configurations of Cascade R-CNN can also be seen in the configs folder and training them should be quite straight forward. Simply, adapt them to the dataset you want to train on and it should work out of the box.
