### ISSUE TITLE
Impact of mean_teacher on the training process

### ISSUE THREAD

**Issue by qraleq** [hasanirtiza/Pedestron#151]
Hi, thank you very much for all the insights that you shared from your research.

I'm interested in how mean_teacher impacts the training performance. Do you have comparison between a training without mean_teacher and with mean_teacher?

Thank you very much.

**Comment by hasanirtiza** [comment]
Hi,
I do not remember the numbers now, but as for the accuracy on the validation set is considered, it was around 1-3% LAMR  points inferior, without the mean teacher on CityPersons.
