### ISSUE TITLE
CSP pretrained weights

### ISSUE THREAD

**Issue by Simardeep27** [hasanirtiza/Pedestron#152]
Hi, 
I was reading the paper "Pedestrian Detection: Domain Generalization, CNN, Transformers and Beyond". In the Table 14, you mentioned a model with CSP method and training on Wider Pedestrian, ECP then CP and having a reasonable score of 7.1. Can you please share the pretrained model for the same?

**Comment by hasanirtiza** [comment]
Hi,
Unfortunately, we do not have access to the weights anymore and they cant be provided.
