### ISSUE TITLE
CPU Inference

### ISSUE THREAD

**Issue by mmaaz60** [hasanirtiza/Pedestron#16]
Hi,

Thank you for the great work. Does this repository support inference on CPU for available pedestrian/person detection models? From the installation instructions, it looks like it can only run on GPUs. If that is the case, are you planning to add CPU Inference Support in the near future?

**Stay Safe,**
M Maaz

**Comment by hasanirtiza** [comment]
have a look at #7. Maaz, at the  moment we do not plan to release a cpu-only version. However, we do welcome any community support.
