### ISSUE TITLE
Runtime error - Training with EuroCity persons

### ISSUE THREAD

**Issue by PriyamvadhaK** [hasanirtiza/Pedestron#160]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help. -> yes
2. The bug has not been fixed in the latest version. -> <es

**Describe the bug**
Running the train script with the Eurocity persons dataset using either cascade net or fasterrcnn has some issue - RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'

**Reproduction**
1. What command or script did you run?
```
conda run python tools/train.py configs/elephant/eurocity/faster_rcnn_hrnet.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified? No, did not modify anything

4. What dataset did you use?

**Environment**
 Same as Google collab demo script

**Error traceback**
If applicable, paste the error trackback here.

![image](https://user-images.githubusercontent.com/40832452/226916004-627f5407-f838-47f8-92f5-1c4469173e6b.png)

![image](https://user-images.githubusercontent.com/40832452/226926252-10fd6da5-a614-4e61-8823-7c6a1f052162.png)

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hasanirtiza** [comment]
It’s a known issue. It can be resolved (look at #17 and #60).
