### ISSUE TITLE
What's ignore_other_vru in ECP evaluation?

### ISSUE THREAD

**Issue by yutongy98** [hasanirtiza/Pedestron#162]
Hello thanks again for the great repo! A small question towards the evaluation on eurocity persons dataset: what is the meaning of ignore_other_vru in the 117th line of tools/ECPB/eval.py? More specific, what's vru? 

From the experiments I found setting this variable to True (ignore something) will bring lower LAMR. What's more, the server of ECP used 'False' by default but in pedestron 'True' is used. 

Thanks in advance!

**Comment by hasanirtiza** [comment]
In short: 
param ignore_other_vru: - If true, other VRU ground truth boxes are used during the matching process, therefore other classes (e.g. riders) which are detected and classified as the primary detection class (e.g. pedestrians) do not cause a false positive.


Have a look [here](https://github.com/SomeNeurons/ECPB/blob/340b62b9d904b0fc893b9a6c6d3e15f13914bd2e/params.py).

Very probably, when we cloned that code it was set to True or may be we set it to true for some debugging and just overlooked. In anyways, you can follow numbers of Pedestron on the ECP server. I would suggest to use the params given in the official ECP eval repo.

**Comment by yutongy98** [comment]
Thank you for your answer!
