### ISSUE TITLE
mmdet/ops/roi_align/src/roi_align_kernel.cu(145): error: identifier "THCudaCheck" is undefined

### ISSUE THREAD

**Issue by wangtingwei1993** [hasanirtiza/Pedestron#164]
I am struggling with an error while executing the command 'python setup.py develop' by following the installation guide. It seems that this error is caused by the Pytorch library. I am using Pytorch 1.13.1 for cuda 11.7. Any idea about how to solve this issue? Thanks a lot!

**Comment by hasanirtiza** [comment]
Almost certainly it is related to versions miss match. For starters your pytorch version seem too high. Check the installation file (https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) and also other people have mentioned it check those issues, some instances are [here](https://github.com/open-mmlab/mmdetection/issues/1813) and [here](https://github.com/hasanirtiza/Pedestron/issues/146) for example.
