### ISSUE TITLE
A request for advice on pedestrian tracking work.

### ISSUE THREAD

**Issue by kuangxiaoye** [hasanirtiza/Pedestron#169]
Thank you very much for this great work！

I am currently conducting performance testing on pedestrian tracking related models, but I have not found any pedestrian tracking projects similar to Pedestron.

Do you have any recommendations for related projects?

**Comment by hasanirtiza** [comment]
Have you tested this [FairMot](https://github.com/ifzhang/FairMOT) ? Else [MMTracking](https://github.com/open-mmlab/mmtracking) might also work, in case you do not know about them already.

**Comment by kuangxiaoye** [comment]
> Have you tested this [FairMot](https://github.com/ifzhang/FairMOT) ? Else [MMTracking](https://github.com/open-mmlab/mmtracking) might also work, in case you do not know about them already.

Thank you very much. As you can see, you have adapted a new model through mmdetection.

I hope to find a project that has updated tracking algorithms through mmtracking.

However, I can also try to complete this work. Thank you for your attention.
