### ISSUE TITLE
Can you provide the code to convert the original annotations of the ECP dataset into COCO format (including vis_ratio)?

### ISSUE THREAD

**Issue by eorroot** [hasanirtiza/Pedestron#172]
Thank you very much for the json file that converts the annotations of the ECP dataset into COCO format. I am a bit confused that the annotations for the ECP dataset do not provide exact information on vis_ratio and occ, only approximate occ information,, but I see that the Pedestron/datasets/EruoCity/day_val_visT.json file you provided contains explicit vis_ratio information.

**Comment by hasanirtiza** [comment]
This is the script we used to convert the annotations, (tools/convert_datasets/eurocity/convert_eurocity_to_coco.py). On quick look, doesn't appear to me that we extracted exact vis ratio.

**Comment by eorroot** [comment]
> This is the script we used to convert the annotations, (tools/convert_datasets/eurocity/convert_eurocity_to_coco.py). On quick look, doesn't appear to me that we extracted exact vis ratio.
![1720656965588](https://github.com/hasanirtiza/Pedestron/assets/49010412/167a3d33-6736-40f6-aebb-241629c7757e)
![image](https://github.com/hasanirtiza/Pedestron/assets/49010412/e652a329-5c83-4a7e-ad9b-e0d3453f78d0)

Thank you very much for your reply. 

Maybe you misunderstood what I meant. What I mean is that I found two kinds of comments (day_val.json, day_val_visT.json) in (Pedestron/datasets/EuroCity/) about ECP validation sets (I provided the images for your convenience).

I took a quick look at (tools/convert_datasets/eurocity/convert_eurocity_to_coco.py) and it seems that the conversion is to the day_val.json version. And the conversion to day_val_visT.json (which contains the vis_ratio) has no corresponding script . Maybe, you forgot to update it.

**Comment by hasanirtiza** [comment]
Now it is clear, these file were added by another researcher @AbdulHannanKhan to the repo, please contact him on how he computed this vis ratio (potentially could be through segmentation, or may be he contacted the benchmark publishers).
