### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by eguoguo321** [hasanirtiza/Pedestron#19]
Thanks for your great project,but I got some problem with it.
I just clone a project ,download some pre-trained mode ,but some error happended
I'd appreciate if you can help me

**Describe the bug**
I've tired 3 pretrained-mode you provided,but I got same error:
' Class names are not saved in the checkpoint's meta data'

**Reproduction**
1. What command or script did you run?
When I use
```
 python tools/demo.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_5.pth.stu demo/ result_demo/ 
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
I just clone your project,and run a demo
**Environment**
 - OS: redhat
 - GCC gcc version :4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
 - PyTorch version :1.4.0
- How you installed PyTorch :pip
- GPU model :p100
- CUDA and CUDNN version :cuda 9 and cudnn 7.1.x
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
['demo/1.png', 'demo/2.png', 'demo/3.png']
The model and loaded state dict do not match exactly

unexpected key in source state_dict: mask_head.0.conv_res.conv.weight, mask_head.0.conv_res.conv.bias, mask_head.1.conv_res.conv.weight, mask_head.1.conv_res.conv.bias, mask_head.2.conv_res.conv.weight, mask_head.2.conv_res.conv.bias

/DATA/app/OCR/Pedestron/Pedestron/tools/../mmdet/apis/inference.py:40: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
[                                                  ] 0/3, elapsed: 0s, ETA:/DATA/app/anaconda3/envs/pytorch886/lib/python3.6/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Segmentation fault
```

**Bug fix**

**Comment by hasanirtiza** [comment]
First full marks for error template. Thumbs up, that is how all errors should be reported. ` Class names are not saved in the checkpoint's meta data` this a warning, ignore it or refer to [this](https://github.com/open-mmlab/mmdetection/issues/822) for details. Your main problem is `Segmentation fault`, my first guess is that it is your gcc version that is causing it, upgrade it to above 4.9. Also, see [this](https://github.com/open-mmlab/mmdetection/issues/288) and follow the solution.

**Comment by eguoguo321** [comment]
> First full marks for error template. Thumbs up, that is how all errors should be reported. ` Class names are not saved in the checkpoint's meta data` this a warning, ignore it or refer to [this](https://github.com/open-mmlab/mmdetection/issues/822) for details. Your main problem is `Segmentation fault`, my first guess is that it is your gcc version that is causing it, upgrade it to above 4.9. Also see [this](https://github.com/open-mmlab/mmdetection/issues/288) and follwo the solution.

Thanks for your reply, that's really helpful.
I'll follow that issue to try!
thx
