### ISSUE TITLE
Testing for crowd human dataset

### ISSUE THREAD

**Issue by annie7777** [hasanirtiza/Pedestron#20]
Hi I am trying to use test_crowdhuman.py for crowdhumandataset. However, I found the model listed in the repo having '.stu'. so when I run 'python tools/test_crowdhuman.py configs/elephant/crowdhuman/cascade_hrnet.py ./models_pretrained/crowdhuman/epoch_ 19 20 --out 'result.json'. It just got stuck after printing 'index created' I tried test_wider.py which doesn't have any problem, The model for wider faces doesn't have '*.stu' in this name. Also searched in the issues and you said can simply rename 'epoch_19.pth.stu' to 'epoch_19.pth' here (https://github.com/hasanirtiza/Pedestron/issues/17#issuecomment-625407048). I tried but it just gave me this error
'Traceback (most recent call last):
  File "tools/test_crowdhuman.py", line 226, in <module>
    main()
  File "tools/test_crowdhuman.py", line 188, in main
    if 'CLASSES' in checkpoint['meta']:
KeyError: 'meta'
'
demo.py is no problem when using 'epoch_19.pth.stu'.

Would appreciate any help. Thanks!

**Comment by hasanirtiza** [comment]
If you look at this magic [line](https://github.com/hasanirtiza/Pedestron/blob/72f39196b113cd2affaec89d4e162b21ed376188/tools/test_crowdhuman.py#L183) you will know why it get stuck. It searches for i+1 (epoch_20.pth) model, if not found it sleeps and check again and so on. Scroll to the end of [README.MD](https://github.com/hasanirtiza/Pedestron) to see how to run test on crowdhuman.
