### ISSUE TITLE
Will Pedestron be upgraded to support MMDetection V2.0 (Pytorch 1.5 Cuda 10.2)?

### ISSUE THREAD

**Issue by ShaneGilroy** [hasanirtiza/Pedestron#23]
Hi,
Excellent work with Pedestron, I am looking forward to getting it up and running. I am just emailing to see if you have any plans in the near future to upgrade Pedestron to work with the recently upgraded mmdetection V2.0 (Cuda 10.2, Pytorch 1.5)?

**Comment by hasanirtiza** [comment]
This is a good question. We definitely plan to and are currently working towards the overhaul of Pedestron to the latest version of mmdetection. However, this will take sometime. Hard to give a date as of now, but it will definitely happen. One more thing, we are going to add certain configs in near future that are inspired from mmdetection latest version. Just keep checking the repo.
