### ISSUE TITLE
rider affect

### ISSUE THREAD

**Issue by meixitu** [hasanirtiza/Pedestron#24]
Hi @hasanirtiza ,
    Sorry to bother you again, I have an question about WiderPedestrian and cityperson dataset
1. In WiderPedestrian 2019 dataset, both pedestrian and rider have the same label
2. In Cityperson dataset, pedestrian label is 1, rider label is 2

When we use widerpedestrian 2019 to train, and we use cityperson dataset to test, the model will detect the rider as pedestrian. Is it any side affect for cityperson test?

Thanks
Meixitu

**Comment by hasanirtiza** [comment]
Based on the CityPersons [paper](https://arxiv.org/pdf/1702.05693.pdf), section 3.3, it states:
`"While evaluating pedestrian detection
performance, cyclists/sitting persons/other persons/ignore
regions are not considered, which means detections matching with those areas are not counted as mistakes."`

**Comment by meixitu** [comment]
Yes, actually I read the paper yesterday, but I did not notice this sections.

Thanks
Meixitu
