### ISSUE TITLE
Could you share setting for RetinaNet?

### ISSUE THREAD

**Issue by oujieww** [hasanirtiza/Pedestron#3]
Thank you  share your nice work! Could you  share us how to choose setting for RetinaNet, i have try some , but not good .so ~~~ i come here again, looking for help.

**Comment by hasanirtiza** [comment]
We have added configs for RetinaNet along with a pre-trained model. We might at some point in future update a better pre-trained model for RetinaNet.

**Comment by oujieww** [comment]
@hasanirtiza thank you so much

**Comment by oujieww** [comment]
@hasanirtiza  could you share the train log file , i use your config , but cannot converge.

**Comment by hasanirtiza** [comment]
@oujieww Unfortunately we do not have the training log as of now, due to limited access (pandemic). 
How many GPUs are you using ?
Something that might help, try pre-training or refer to our [ArXiv](https://arxiv.org/pdf/2003.08799.pdf) pre-print for details on how to pre-train.

**Comment by oujieww** [comment]
@hasanirtiza  i use 4 gpus (1080Ti), only use imagenet pre-training for backbone, batch size=1 for  each gpu. thank you for your nice reply, i should read your paper more carefully.

**Comment by oujieww** [comment]
I hope the epidemic there will be passed as soon as possible. Best wishes to you.
