### ISSUE TITLE
How can we support Pedestron ? Community support etc ?

### ISSUE THREAD

**Issue by AyeshaNirma** [hasanirtiza/Pedestron#30]
I would lyk to know, how can we support Pedestron (community support act)?

**Comment by hasanirtiza** [comment]
I dont know, maybe by Starring the repo ? 
I mean we are open to any suggestions, pull requests, feature enhancement or general discussions. Moreover if there are some other datasets and you would like to add its support (share processed annotations or configs etc.) to the Pedestron, you guys are welcome and we would be happy to collaborate if possible.  Drop us an email at: ihasan085@gmail.com

**Comment by xtzd** [comment]
Hi, are there any plans to build a docker from this repo in the future?

**Comment by hasanirtiza** [comment]
This is a good point. Probably, in future we will provide docker image. By the way, did you try building with this [docker image](https://mmdetection.readthedocs.io/en/latest/install.html#another-option-docker-image).

**Comment by gustavofuhr** [comment]
@xtzd I tried to do it here: https://github.com/hasanirtiza/Pedestron/issues/175
