### ISSUE TITLE
when i try to train faster-rcnn on cityperson datasets ,but i got an AttributeErrror

### ISSUE THREAD

**Issue by ggy112** [hasanirtiza/Pedestron#31]
'Mean_teacher_Runner' object has no attribute 'register_lr_hooks'

**Comment by ggy112** [comment]
![捕获](https://user-images.githubusercontent.com/45276435/82280799-52cb9400-99c2-11ea-81d2-88bf57a422f0.PNG)

**Comment by ggy112** [comment]
![捕获](https://user-images.githubusercontent.com/45276435/82280923-9d4d1080-99c2-11ea-962c-772fe3274418.PNG)

**Comment by hasanirtiza** [comment]
Did you install properly? Secondly, did you manage to run the demo.py correctly using any of the pre-trained model ? From the error, it appears that there is some issue either in the installation or the version of mmcv or mmdet is not what it should be ?

**Comment by chengjuzhou** [comment]
hwo about change 'register_lr_hooks' to 'register_lr_hook'?

**Comment by hasanirtiza** [comment]
No, it should run with the `register_lr_hooks`. Given, its installed correctly. Check your mmcv version, we have tested it with 0.2.14 and 0.2.10.

**Comment by ggy112** [comment]
thank you very much , i change the mmcv version into 0.2.14 ,that's work.
