### ISSUE TITLE
KeyError: 'CosinLrUpdaterHook is not in the hook registry

### ISSUE THREAD

**Issue by chengjuzhou** [hasanirtiza/Pedestron#32]
![image](https://user-images.githubusercontent.com/16832162/82323659-fb9de180-9a0a-11ea-90b9-0eae99752638.png)

When I try to train cascade_hrnet.py, encounter above error. It seems that there is no corresponding lr schedule

**Comment by hasanirtiza** [comment]
You are using mmcv==0.4.4. You need  to revert back to  mmcv==0.2.14.
#11

**Comment by chengjuzhou** [comment]
> You are using mmcv==0.4.4. You need to revert back to mmcv==0.2.14.
> #11

Thanks, it works well after degrading mmcv
