### ISSUE TITLE
setting of training set 

### ISSUE THREAD

**Issue by Jokoe66** [hasanirtiza/Pedestron#34]
The training sets of CityPersons and Caltech benchmarks currently used in Pedestron are the **Reasonable** subsets (h>=50 and vis>=0.65), right ? Do you have any plan to train the detectors on other training subsets?  Since when training occlusion-handling detectors (like JL-TopS, PDOE, MGAN), the subset (h>=50 and vis >=0.3) is commonly used.

**Comment by hasanirtiza** [comment]
You can look at the conversion scripts, for example [convert_cityperson_to_coco.py](https://github.com/hasanirtiza/Pedestron/tree/master/tools/convert_datasets/citypersons) to see. In our case, for CityPersons, we only prune based on height >= 50 and not on the visibility, for achieving an overall decent performance across all splits.

**Comment by Jokoe66** [comment]
OK, but I wonder if the current data augmentation (particularly the random crop) strategy is suitable in such case. For example, the cropped patch may contain no visible part of a heavily occluded person, which will introduce persons with visibility 0 and cause classification ambiguity. 

By the way, I find that the [implemented random crop](https://github.com/hasanirtiza/Pedestron/blob/master/mmdet/datasets/extra_aug.py#L122) seems to be problematic. The cropped patch satisfies when **any** bbox has an IoU greater than the min_iou. But in the current implementation, the cropped patch satisfies when **all** bboxes have IoUs greater than min_iou. See [this issue](https://github.com/amdegroot/ssd.pytorch/issues/119).

**Comment by hasanirtiza** [comment]
I mean number of severely occluded cases for e.g (vis <40 %) are close to ~10 % in cityPersons and this is randomly cropping so I am not sure how much an impact it would practically have. Moreover, as far as I remember we did see empirically a small gain by incorporating this augmentation. Perhaps you can give it a shot without this augmentation as well.

Regarding the potential bug, we actually over looked it. Support appreciated.

**Comment by Jokoe66** [comment]
Yeah. The actual impact of these problems is probably small. Thanks.
