### ISSUE TITLE
Learning schedule for retinanet

### ISSUE THREAD

**Issue by zyayoung** [hasanirtiza/Pedestron#37]
https://github.com/hasanirtiza/Pedestron/blob/b66c01641249943bbdce495c227fbd500b1ac992/configs/elephant/cityperson/ga_retinanet_ResNeXt101.py#L132

It seems that the network is under-trained following the learning schedule in config.
Is this the schedule applied to produce the result in README? Does the batch size (with linear lr scaling) greatly affect the result?

**Comment by hasanirtiza** [comment]
Valid observation. With ga_retinanet, we faced some issues during optimization. We did not try a thorough grid search of the hyper parameters, but a few lrs and steps. This seem to work reasonably well in this case and we are still experimenting over hyper parameters. You can try to play around and feel free to let us know, if you find something better. The AP reported in the README.md is produces using this config. Regarding the batch size with linear scaling, in our experience, overall for all models, **it did effect but not significantly**, to give you an idea, may be around 0.5-1.2% MR points in some cases.
