### ISSUE TITLE
AP for cityperson

### ISSUE THREAD

**Issue by ggy112** [hasanirtiza/Pedestron#38]
Sorry to bother you  but I have an issue when calculating the AP value for cityperson.  
what should i do ? i have tried  CUDA_VISIBLE_DEVICES=0 python tools/test_city_person.py  config checkpoint start checkpoin_end --result.pickle --eval bbox.

**Comment by hasanirtiza** [comment]
Have a look at REDAME.md, especially testing section. For staters, CityPerson is usually evaluated using Log Average Miss Rate not AP. This is the command you should run to evaluate

```shell
python ./tools/test_city_person.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_ 5 6\
 --out result_citypersons.json --mean_teacher 
```
 If you want to evaluate AP you need to use tools/test.py (you might have to change some fields in annotation file).

**Comment by ggy112** [comment]
ok , thank you!
