### ISSUE TITLE
When I use faster_rcnn_hrnet to test cityperson, i got an error

### ISSUE THREAD

**Issue by ggy112** [hasanirtiza/Pedestron#39]
![image](https://user-images.githubusercontent.com/45276435/83645026-8cb4b100-a5e4-11ea-8870-702bf10f1c5f.png)

![image](https://user-images.githubusercontent.com/45276435/83645090-a229db00-a5e4-11ea-9a29-5dc29602faa5.png)

**Comment by ggy112** [comment]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 500/500, 1.8 task/s, elapsed: 278s, ETA:     0sTraceback (most recent call last):
  File "tools/test_city_person.py", line 226, in <module>
    main()
  File "tools/test_city_person.py", line 220, in main
    MRs = validate('datasets/CityPersons/val_gt.json', args.out)
  File "/root/Desktop/Pedestron-master/tools/cityPerson/eval_demo.py", line 11, in validate
    cocoDt = cocoGt.loadRes(dt_path)
  File "/root/Desktop/Pedestron-master/tools/cityPerson/coco.py", line 313, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by ggy112** [comment]
i have fixed it

**Comment by hasanirtiza** [comment]
Could you share details ? So someone else running into, knows the solution.

**Comment by msha096** [comment]
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 500/500, 1.8 task/s, elapsed: 278s, ETA: 0sTraceback (most recent call last):
> File "tools/test_city_person.py", line 226, in
> main()
> File "tools/test_city_person.py", line 220, in main
> MRs = validate('datasets/CityPersons/val_gt.json', args.out)
> File "/root/Desktop/Pedestron-master/tools/cityPerson/eval_demo.py", line 11, in validate
> cocoDt = cocoGt.loadRes(dt_path)
> File "/root/Desktop/Pedestron-master/tools/cityPerson/coco.py", line 313, in loadRes
> if 'caption' in anns[0]:
> IndexError: list index out of range

Hi,

I am having the same problem with you, could you please tell me how you fix that bug? Thank you!

**Comment by BehdadSDP** [comment]
> > [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 500/500, 1.8 task/s, elapsed: 278s, ETA: 0sTraceback (most recent call last):
> > File "tools/test_city_person.py", line 226, in
> > main()
> > File "tools/test_city_person.py", line 220, in main
> > MRs = validate('datasets/CityPersons/val_gt.json', args.out)
> > File "/root/Desktop/Pedestron-master/tools/cityPerson/eval_demo.py", line 11, in validate
> > cocoDt = cocoGt.loadRes(dt_path)
> > File "/root/Desktop/Pedestron-master/tools/cityPerson/coco.py", line 313, in loadRes
> > if 'caption' in anns[0]:
> > IndexError: list index out of range
> 
> Hi,
> 
> I am having the same problem with you, could you please tell me how you fix that bug? Thank you!

Hi :) 
Do you remember fix this problem or not? :))
