### ISSUE TITLE
Clearer mapping between weights and configs

### ISSUE THREAD

**Issue by pietz** [hasanirtiza/Pedestron#41]
I may have just missed it but it's often not clear to me which weight file hosted on Google Drive relates to which config script in the repo. Could you provide another table for this?

Thanks,

**Comment by hasanirtiza** [comment]
Have a look at the the first benchmarking table, besides each detector (first column) you have the dataset name(you should go to this folder in elephant directory) and name of the backbone (third column) which is the config file, thats actually all you need. Anyways, perhaps it is a bit tricky to follow, we will try to come up with something clearer.

**Comment by pietz** [comment]
Ah perfect, thanks. I didn’t look into the elephant dir.

Thank you for your work!

Best,
Paul
