### ISSUE TITLE
How to extract features from Pedestron?

### ISSUE THREAD

**Issue by gokulanv** [hasanirtiza/Pedestron#42]
I want to get the features from Pedestron that helps the model identify the persons. Like the features that help identify just the persons accurately.
 
I think mmlab gets its features from - 
[feature_extractor](https://github.com/open-mmlab/mmdetection/blob/51df8a9b7ad5f25ebd75cf8e0969c3b728bde08d/mmdet/models/detectors/single_stage.py#L75).

Can you please suggest me how those features can be extracted? Or Where to look at to know more about that?

**Comment by hasanirtiza** [comment]
It is similar to the example you provided of mmlab. Additionally, for any backbone you can also simply return the feature map (for whatever layer you want) as an additional output. 

Moreover, have a look at any detector and see how are they using it:

```shell

def extract_feat(self, img):
        x = self.backbone(img)
        if self.with_neck:
            x = self.neck(x)
        return x
```

Also have a look [here under the section Write a new model](https://github.com/hasanirtiza/Pedestron/blob/2cd4bc0b6c4f8f9c068aca6e404093bcc1bfccb2/TECHNICAL_DETAILS.md#write-a-new-model) or [here](https://github.com/hasanirtiza/Pedestron/blob/2cd4bc0b6c4f8f9c068aca6e404093bcc1bfccb2/mmdet/models/detectors/cascade_rcnn.py#L114)

**Comment by gokulanv** [comment]
Can I still be able to do the same if I am using a pre-trained model? Because, right now, I just feed the image to the model trained on CrowdHuman(2) dataset and it just returns the output. How do I get the features when I use the pre-trained model?

**Comment by hasanirtiza** [comment]
Of course, you should be able to do it with the pre-trained model as well. I am not 100% sure if I understood your previous comment correctly, but did you try using extract_feat() method ?
