### ISSUE TITLE
what is the flag mean_teacher for?

### ISSUE THREAD

**Issue by twmht** [hasanirtiza/Pedestron#43]
Hi,

I found that the network would output two pths, one is for teacher, and the other is for student. Do you have any reference for their difference?

**Comment by hasanirtiza** [comment]
In both models, weights are saved slightly differently. It is a method that does some sort of smoothing of weights during training and they are helpful. You can read more about it in this [NIPS paper](https://papers.nips.cc/paper/6719-mean-teachers-are-better-role-models-weight-averaged-consistency-targets-improve-semi-supervised-deep-learning-results.pdf)

_Originally posted by @hasanirtiza in https://github.com/hasanirtiza/Pedestron/issues/17#issuecomment-643080403_
