### ISSUE TITLE
MR of Caltech dataset

### ISSUE THREAD

**Issue by ggy112** [hasanirtiza/Pedestron#45]
i use the pretrianed model(Cascade Mask R-CNN | Caltech | HRNet | 1.7 | 25.7) you provided. 
But the MR i got is R:17%;HO:58%. far from the R:1.7% and HO:25.7%

**Comment by hasanirtiza** [comment]
Are you sure you used the new annotations ? or the the annotations we provide. Moreover, have you read this issue ? #5

**Comment by ggy112** [comment]
thank you very much!

**Comment by hasanirtiza** [comment]
Is it solved ?
