### ISSUE TITLE
Maxium GPU memory requirement for Cascade Mask R-CNN with HRNet on CityPersons dataset

### ISSUE THREAD

**Issue by chengjuzhou** [hasanirtiza/Pedestron#52]
Hi, how much GPU memory used in your training? I tried to use 1080Ti to train Cascade Mask R-CNN with HRNet, but met with out of memory. The Cascade Mask R-CNN with MobileNet also has the problem of out of memory for 2 image per GPU.

**Comment by hasanirtiza** [comment]
Reduce the batch size to one image per gpu, it should work, if not, then you might want to reduce the image size(maintaining the aspect ratio ideally).
