### ISSUE TITLE
How much GPU memory do I need

### ISSUE THREAD

**Issue by yuanvq** [hasanirtiza/Pedestron#53]
How much GPU memory do I need if i want to run  ’python tools/train.py configs/elephant/cityperson/cascade_hrnet.py‘。
I got error like this ’RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 7.92 GiB total capacity; 7.06 GiB already allocated; 11.75 MiB free; 299.73 MiB cached)‘

**Comment by hasanirtiza** [comment]
Currently, I cannot run, we had DGX, Tesla V-100(~32480MiB) and we could run 2 imgs per gpu. With your cards, I would recommend 2 things:
1) Reduce batch size to a single img per gpu
2) If 1 not does not solve, reduce the image resolution #52

**Comment by yuanvq** [comment]
thank you so much

**Comment by yuanvq** [comment]
@hasanirtiza thank you so much
