### ISSUE TITLE
# TODO: remove the restriction of imgs_per_gpu == 1 when prepared

### ISSUE THREAD

**Issue by r0mer0m** [hasanirtiza/Pedestron#54]
Hello,

I am trying to run batch-inference. I saw a comment in the source code at `mmdet/models/detectors/base.py` saying "# TODO: remove the restriction of imgs_per_gpu == 1 when prepared". Just want to double check it is safe to remove the assertion by us.

Best, 
Miguel

**Comment by hasanirtiza** [comment]
Actually, never tried it. Its a comment by the mmdet authors and it is still present in the [latest version](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py). Never bothered me. No harm in trying to remove and see by your self.
