### ISSUE TITLE
Where is CrowdHuman implemented in mmdet/datasets? 

### ISSUE THREAD

**Issue by dtch1997** [hasanirtiza/Pedestron#56]
I am working on a fork of your repo and would like to add a small CrowdHuman subset (100 train images, 100 val images) for debug purposes. I couldn't find any documentation in this repo so I referred to the MMDetection instructions [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_dataset.md).

To implement this debug dataset, I would like to know how the current CrowdHuman dataset is implemented since it should be a simple copy-paste. However I couldn't find any implementation inside `Pedestron/mmdet/datasets`. Where can I find the reference code that implements CrowdHuman dataset?

**Comment by dtch1997** [comment]
I figured this out after looking at `configs/elephant/crowdhuman/cascase_hrnet.py`. Basically CrowdHuman dataset is implemented as a `CocoDataset`.

**Comment by hasanirtiza** [comment]
Pedestron is built on the idea that every dataset is converted into COCO format. Currently, the CrowdHuman datastet is also converted into COCO format. Additionally, if you want to generate a subset you can have a look at our [datasets conversion tools](https://github.com/hasanirtiza/Pedestron/tree/master/tools/convert_datasets/crowdhuman).
