### ISSUE TITLE
How to set SSDHead parameters in model config?

### ISSUE THREAD

**Issue by dtch1997** [hasanirtiza/Pedestron#57]
I am looking at `configs/ssd300_coco.py` as a reference. 
```
input_size = 300
model = dict(
    type='SingleStageDetector',
    pretrained='open-mmlab://vgg16_caffe',
    backbone=dict(
        type='SSDVGG',
        input_size=input_size,
        depth=16,
        with_last_pool=False,
        ceil_mode=True,
        out_indices=(3, 4),
        out_feature_indices=(22, 34),
        l2_norm_scale=20),
    neck=None,
    bbox_head=dict(
        type='SSDHead',
        input_size=input_size,
        in_channels=(512, 1024, 512, 256, 256, 256),
        num_classes=81,
        anchor_strides=(8, 16, 32, 64, 100, 300),
        basesize_ratio_range=(0.15, 0.9),
        anchor_ratios=([2], [2, 3], [2, 3], [2, 3], [2], [2]),
        target_means=(.0, .0, .0, .0),
        target_stds=(0.1, 0.1, 0.2, 0.2)))
```
How are the arguments for `SSDHead` determined? If I were to change the backbone to `Mobilenet` and change the input size fom `300` to `128`, how should I modify the default values of `in_channels`, `anchor_strides`, etc.

**Comment by dtch1997** [comment]
Trying to run with `input_size=128` results in the following error: 
```
  File "/home/dtch009/Pedestron/mmdet/models/anchor_heads/ssd_head.py", line 76, in __init__
    base_size = min_sizes[k]
IndexError: list index out of range
```
After looking more closely at `mmdet/models/anchor_heads/ssd_head.py`, it seems like this is because SSDHead is hardcoded to have input size of 300 or 512, as seen from the following code snippet; 
```
        if input_size == 300:
            if basesize_ratio_range[0] == 0.15:  # SSD300 COCO
                min_sizes.insert(0, int(input_size * 7 / 100))
                max_sizes.insert(0, int(input_size * 15 / 100))
            elif basesize_ratio_range[0] == 0.2:  # SSD300 VOC
                min_sizes.insert(0, int(input_size * 10 / 100))
                max_sizes.insert(0, int(input_size * 20 / 100))
        elif input_size == 512:
            if basesize_ratio_range[0] == 0.1:  # SSD512 COCO
                min_sizes.insert(0, int(input_size * 4 / 100))
                max_sizes.insert(0, int(input_size * 10 / 100))
            elif basesize_ratio_range[0] == 0.15:  # SSD512 VOC
                min_sizes.insert(0, int(input_size * 7 / 100))
                max_sizes.insert(0, int(input_size * 15 / 100))
```
@hasanirtiza can this implementation be changed to allow a wider range of input size?

**Comment by dtch1997** [comment]
I also noticed that the implementation of SSDHead differs significantly from the original MMDetection implementation found [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/ssd_head.py). I haven't tested it but it seems like the original implementation does not require this hardcoding. Maybe that implementation can be adapted?

**Comment by hasanirtiza** [comment]
I suppose, yes it can be adapted. You might need to modify few bits here and there, but in theory you should be able to adapt. As far as the original implementation, this is the newer version of mmdetection you are pointing to, therefore naturally some differences. If I remember it correctly, we have personally tried ssd once in the past but somehow we stopped (probably because of the performance) and opted for RetinaNet. Please, comeback and let us know if you manage to squeeze a decent performance out of ssd and at good computational speed.
