### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Morteza-j8** [hasanirtiza/Pedestron#6]
**I run this command (same as example):**
`$ python3 tools/demo.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_5.pth.stu ../data/person/ result_demo/
../data/person/`

**get me this error:**
```
['../data/person/p3.jpg', '../data/person/p8.jpg', '../data/person/p4.jpg', '../data/person/p2.jpg', '../data/person/p1.jpg', '../data/person/p10.jpg', '../data/person/p7.jpg', '../data/person/p6.jpg', '../data/person/p9.jpg', '../data/person/p5.jpg', '../data/person/p11.jpg']
unexpected key in source state_dict: mask_head.0.conv_res.conv.weight, mask_head.0.conv_res.conv.bias, mask_head.1.conv_res.conv.weight, mask_head.1.conv_res.conv.bias, mask_head.2.conv_res.conv.weight, mask_head.2.conv_res.conv.bias

./Pedestron-master/tools/../mmdet/apis/inference.py:39: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
[                                                  ] 0/11, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/demo.py", line 67, in <module>
    run_detector_on_dataset()
  File "tools/demo.py", line 63, in run_detector_on_dataset
    detections = mock_detector(model, im, output_dir)
  File "tools/demo.py", line 37, in mock_detector
    results = inference_detector(model, image)
  File "./Pedestron-master/tools/../mmdet/apis/inference.py", line 66, in inference_detector
    return _inference_single(model, imgs, img_transform, device)
  File "./Pedestron-master/tools/../mmdet/apis/inference.py", line 93, in _inference_single
    result = model(return_loss=False, rescale=True, **data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "./Pedestron-master/tools/../mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "./Pedestron-master/tools/../mmdet/models/detectors/base.py", line 88, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "./Pedestron-master/tools/../mmdet/models/detectors/base.py", line 79, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "./Pedestron-master/tools/../mmdet/models/detectors/cascade_rcnn.py", line 241, in simple_test
    x = self.extract_feat(img)
  File "./Pedestron-master/tools/../mmdet/models/detectors/cascade_rcnn.py", line 115, in extract_feat
    x = self.backbone(img)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "./Pedestron-master/tools/../mmdet/models/backbones/hrnet.py", line 446, in forward
    x = self.relu(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/activation.py", line 94, in forward
    return F.relu(input, inplace=self.inplace)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 912, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
my python version is 3.5

**Comment by hasanirtiza** [comment]
Can you share with us your PyTorch and CUDA version. Moreover, also which GPU (V100 etc) are you using ?

**Comment by Morteza-j8** [comment]
> Can you share with us your PyTorch and CUDA version. Moreover, also which GPU (V100 etc) are you using ?

```
$ cat /usr/local/cuda/version.txt
CUDA Version 10.2.89
```

```
$ pip3 show torch torchvision
Name: torch
Version: 1.4.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/morteza/.local/lib/python3.8/site-packages
Requires: 
Required-by: torchvision
---
Name: torchvision
Version: 0.5.0
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: /home/morteza/.local/lib/python3.8/site-packages
Requires: torch, six, pillow, numpy
Required-by: 

```

**Comment by Morteza-j8** [comment]
i used NVIDIA 740M GPU.

**Comment by hasanirtiza** [comment]
Most probably its the CUDA version. We have tested Pedestron with `CUDA 10.0` and `9.0`. I suggest perhaps you revert back to `CUDA 10.0` and recompile it, to test if it works on your machine. Furthermore you can also refer to the following issues (in case you have not seen them already) 
[issue:1](https://github.com/facebookresearch/detectron2/issues/235)
Secondly have a look at the 
[issue:2](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues) 
scroll down to the bottom and look at point 4. See if it also applies to you.

**Comment by Morteza-j8** [comment]
when i wait for your response, i changed my device by config :
OS: ubuntu 16.04
GPU: NVIDIA Quadro-M1000M

CUDA Version: 10.2.89
Python: 3.5
PyTorch: 1.4.0

after run same as previous example get me this error:

RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 1.96 GiB total capacity; 473.88 MiB already allocated; 27.25 MiB free; 480.00 MiB reserved in total by PyTorch)

**Comment by hasanirtiza** [comment]
That is a different problem. I would suggest first simply changing the CUDA version back to 10.0, compiling Pedestron (just to be on the safe side) and see if it works.

**Comment by Morteza-j8** [comment]
i install CUDA version 10.0:
```
$ cat /usr/local/cuda/version.txt 
CUDA Version 10.0.130
```


changed my error:

```
$ python3 tools/demo.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_5.pth.stu demo/ result_demo/ 

Traceback (most recent call last):
  File "tools/demo.py", line 14, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result
  File "./Pedestron-master/tools/../mmdet/apis/__init__.py", line 2, in <module>
    from .train import train_detector
  File "./Pedestron-master/tools/../mmdet/apis/train.py", line 7, in <module>
    from mmdet.core.my_mmcv.runner.mean_teacher_runner import Mean_teacher_Runner as Runner
  File "./Pedestron-master/tools/../mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "./Pedestron-master/tools/../mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "./Pedestron-master/tools/../mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "./Pedestron-master/tools/../mmdet/ops/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "./Pedestron-master/tools/../mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File "./Pedestron-master/tools/../mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from .. import deform_conv_cuda
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

**Comment by hasanirtiza** [comment]
Did you recompile Pedestron after you changed CUDA version ?

**Comment by Morteza-j8** [comment]
`$ sudo python3 setup.py develop`

```
No CUDA runtime is found, using CUDA_HOME='/usr'
Compiling mmdet/ops/nms/src/soft_nms_cpu.pyx because it depends on /usr/local/lib/python3.5/dist-packages/Cython/Includes/numpy/__init__.pxd.
[1/1] Cythonizing mmdet/ops/nms/src/soft_nms_cpu.pyx
running develop
running egg_info
writing top-level names to mmdet.egg-info/top_level.txt
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing mmdet.egg-info/PKG-INFO
writing requirements to mmdet.egg-info/requires.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.nms.soft_nms_cpu' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/morteza/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c mmdet/ops/nms/src/soft_nms_cpu.cpp -o build/temp.linux-x86_64-3.5/mmdet/ops/nms/src/soft_nms_cpu.o -Wno-unused-function -Wno-write-strings -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=soft_nms_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/morteza/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /home/morteza/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/morteza/.local/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from mmdet/ops/nms/src/soft_nms_cpu.cpp:640:
/home/morteza/.local/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
mmdet/ops/nms/src/soft_nms_cpu.cpp: In function ‘PyObject* __pyx_pf_5mmdet_3ops_3nms_12soft_nms_cpu_soft_nms_cpu(PyObject*, PyArrayObject*, float, unsigned int, float, float)’:
mmdet/ops/nms/src/soft_nms_cpu.cpp:2497:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
mmdet/ops/nms/src/soft_nms_cpu.cpp:3008:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.5/mmdet/ops/nms/soft_nms_cpu.cpython-35m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.5/mmdet/ops/nms/soft_nms_cpu.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/nms
copying build/lib.linux-x86_64-3.5/mmdet/ops/roi_align/roi_align_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/roi_align
copying build/lib.linux-x86_64-3.5/mmdet/ops/roi_pool/roi_pool_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/roi_pool
copying build/lib.linux-x86_64-3.5/mmdet/ops/nms/nms_cpu.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/nms
copying build/lib.linux-x86_64-3.5/mmdet/ops/nms/nms_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/nms
copying build/lib.linux-x86_64-3.5/mmdet/ops/dcn/deform_conv_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/dcn
copying build/lib.linux-x86_64-3.5/mmdet/ops/dcn/deform_pool_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/dcn
copying build/lib.linux-x86_64-3.5/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/sigmoid_focal_loss
copying build/lib.linux-x86_64-3.5/mmdet/ops/masked_conv/masked_conv2d_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/masked_conv
Creating /usr/local/lib/python3.5/dist-packages/mmdet.egg-link (link to .)
mmdet 0.6.0+unknown is already the active version in easy-install.pth

Installed /home/morteza/Documents/rajman/Pedestron-master
Processing dependencies for mmdet==0.6.0+unknown
Searching for torch==1.4.0
Best match: torch 1.4.0
Adding torch 1.4.0 to easy-install.pth file
Installing convert-onnx-to-caffe2 script to /usr/local/bin
Installing convert-caffe2-to-onnx script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for pycocotools==2.0.0
Best match: pycocotools 2.0.0
Processing pycocotools-2.0.0-py3.5-linux-x86_64.egg
pycocotools 2.0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/pycocotools-2.0.0-py3.5-linux-x86_64.egg
Searching for terminaltables==3.1.0
Best match: terminaltables 3.1.0
Processing terminaltables-3.1.0-py3.5.egg
terminaltables 3.1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/terminaltables-3.1.0-py3.5.egg
Searching for six==1.14.0
Best match: six 1.14.0
Adding six 1.14.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for matplotlib==1.5.1
Best match: matplotlib 1.5.1
Adding matplotlib 1.5.1 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for numpy==1.18.2
Best match: numpy 1.18.2
Adding numpy 1.18.2 to easy-install.pth file
Installing f2py3.5 script to /usr/local/bin
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin

Using /home/morteza/.local/lib/python3.5/site-packages
Searching for mmcv==0.2.10
Best match: mmcv 0.2.10
Adding mmcv 0.2.10 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for requests==2.23.0
Best match: requests 2.23.0
Adding requests 2.23.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for opencv-python==3.4.2.17
Best match: opencv-python 3.4.2.17
Adding opencv-python 3.4.2.17 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for Cython==0.29.16
Best match: Cython 0.29.16
Adding Cython 0.29.16 to easy-install.pth file
Installing cython script to /usr/local/bin
Installing cygdb script to /usr/local/bin
Installing cythonize script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for addict==2.2.1
Best match: addict 2.2.1
Processing addict-2.2.1-py3.5.egg
addict 2.2.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/addict-2.2.1-py3.5.egg
Searching for PyYAML==3.13
Best match: PyYAML 3.13
Adding PyYAML 3.13 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for certifi==2020.4.5.1
Best match: certifi 2020.4.5.1
Adding certifi 2020.4.5.1 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Finished processing dependencies for mmdet==0.6.0+unknown
```

**Comment by Morteza-j8** [comment]
> Did you recompile Pedestron after you changed CUDA version ?



> That is a different problem. I would suggest first simply changing the CUDA version back to 10.0, compiling Pedestron (just to be on the safe side) and see if it works.

do i  open issue for this problem?

**Comment by hasanirtiza** [comment]
Yes, you can.

**Comment by hasanirtiza** [comment]
> `$ sudo python3 setup.py develop`
> 
> ```
> No CUDA runtime is found, using CUDA_HOME='/usr'
> Compiling mmdet/ops/nms/src/soft_nms_cpu.pyx because it depends on /usr/local/lib/python3.5/dist-packages/Cython/Includes/numpy/__init__.pxd.
> [1/1] Cythonizing mmdet/ops/nms/src/soft_nms_cpu.pyx
> running develop
> running egg_info
> writing top-level names to mmdet.egg-info/top_level.txt
> writing dependency_links to mmdet.egg-info/dependency_links.txt
> writing mmdet.egg-info/PKG-INFO
> writing requirements to mmdet.egg-info/requires.txt
> reading manifest file 'mmdet.egg-info/SOURCES.txt'
> writing manifest file 'mmdet.egg-info/SOURCES.txt'
> running build_ext
> building 'mmdet.ops.nms.soft_nms_cpu' extension
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/morteza/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c mmdet/ops/nms/src/soft_nms_cpu.cpp -o build/temp.linux-x86_64-3.5/mmdet/ops/nms/src/soft_nms_cpu.o -Wno-unused-function -Wno-write-strings -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=soft_nms_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/morteza/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
>                  from /home/morteza/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
>                  from /home/morteza/.local/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from mmdet/ops/nms/src/soft_nms_cpu.cpp:640:
> /home/morteza/.local/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>  #warning "Using deprecated NumPy API, disable it with " \
>   ^
> mmdet/ops/nms/src/soft_nms_cpu.cpp: In function ‘PyObject* __pyx_pf_5mmdet_3ops_3nms_12soft_nms_cpu_soft_nms_cpu(PyObject*, PyArrayObject*, float, unsigned int, float, float)’:
> mmdet/ops/nms/src/soft_nms_cpu.cpp:2497:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
>                                   ^
> mmdet/ops/nms/src/soft_nms_cpu.cpp:3008:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
>                                   ^
> x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.5/mmdet/ops/nms/soft_nms_cpu.cpython-35m-x86_64-linux-gnu.so
> copying build/lib.linux-x86_64-3.5/mmdet/ops/nms/soft_nms_cpu.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/nms
> copying build/lib.linux-x86_64-3.5/mmdet/ops/roi_align/roi_align_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/roi_align
> copying build/lib.linux-x86_64-3.5/mmdet/ops/roi_pool/roi_pool_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/roi_pool
> copying build/lib.linux-x86_64-3.5/mmdet/ops/nms/nms_cpu.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/nms
> copying build/lib.linux-x86_64-3.5/mmdet/ops/nms/nms_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/nms
> copying build/lib.linux-x86_64-3.5/mmdet/ops/dcn/deform_conv_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/dcn
> copying build/lib.linux-x86_64-3.5/mmdet/ops/dcn/deform_pool_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/dcn
> copying build/lib.linux-x86_64-3.5/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/sigmoid_focal_loss
> copying build/lib.linux-x86_64-3.5/mmdet/ops/masked_conv/masked_conv2d_cuda.cpython-35m-x86_64-linux-gnu.so -> mmdet/ops/masked_conv
> Creating /usr/local/lib/python3.5/dist-packages/mmdet.egg-link (link to .)
> mmdet 0.6.0+unknown is already the active version in easy-install.pth
> 
> Installed /home/morteza/Documents/rajman/Pedestron-master
> Processing dependencies for mmdet==0.6.0+unknown
> Searching for torch==1.4.0
> Best match: torch 1.4.0
> Adding torch 1.4.0 to easy-install.pth file
> Installing convert-onnx-to-caffe2 script to /usr/local/bin
> Installing convert-caffe2-to-onnx script to /usr/local/bin
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for pycocotools==2.0.0
> Best match: pycocotools 2.0.0
> Processing pycocotools-2.0.0-py3.5-linux-x86_64.egg
> pycocotools 2.0.0 is already the active version in easy-install.pth
> 
> Using /usr/local/lib/python3.5/dist-packages/pycocotools-2.0.0-py3.5-linux-x86_64.egg
> Searching for terminaltables==3.1.0
> Best match: terminaltables 3.1.0
> Processing terminaltables-3.1.0-py3.5.egg
> terminaltables 3.1.0 is already the active version in easy-install.pth
> 
> Using /usr/local/lib/python3.5/dist-packages/terminaltables-3.1.0-py3.5.egg
> Searching for six==1.14.0
> Best match: six 1.14.0
> Adding six 1.14.0 to easy-install.pth file
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for matplotlib==1.5.1
> Best match: matplotlib 1.5.1
> Adding matplotlib 1.5.1 to easy-install.pth file
> 
> Using /usr/lib/python3/dist-packages
> Searching for numpy==1.18.2
> Best match: numpy 1.18.2
> Adding numpy 1.18.2 to easy-install.pth file
> Installing f2py3.5 script to /usr/local/bin
> Installing f2py script to /usr/local/bin
> Installing f2py3 script to /usr/local/bin
> 
> Using /home/morteza/.local/lib/python3.5/site-packages
> Searching for mmcv==0.2.10
> Best match: mmcv 0.2.10
> Adding mmcv 0.2.10 to easy-install.pth file
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for requests==2.23.0
> Best match: requests 2.23.0
> Adding requests 2.23.0 to easy-install.pth file
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for opencv-python==3.4.2.17
> Best match: opencv-python 3.4.2.17
> Adding opencv-python 3.4.2.17 to easy-install.pth file
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for Cython==0.29.16
> Best match: Cython 0.29.16
> Adding Cython 0.29.16 to easy-install.pth file
> Installing cython script to /usr/local/bin
> Installing cygdb script to /usr/local/bin
> Installing cythonize script to /usr/local/bin
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for addict==2.2.1
> Best match: addict 2.2.1
> Processing addict-2.2.1-py3.5.egg
> addict 2.2.1 is already the active version in easy-install.pth
> 
> Using /usr/local/lib/python3.5/dist-packages/addict-2.2.1-py3.5.egg
> Searching for PyYAML==3.13
> Best match: PyYAML 3.13
> Adding PyYAML 3.13 to easy-install.pth file
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for urllib3==1.22
> Best match: urllib3 1.22
> Adding urllib3 1.22 to easy-install.pth file
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for chardet==3.0.4
> Best match: chardet 3.0.4
> Adding chardet 3.0.4 to easy-install.pth file
> Installing chardetect script to /usr/local/bin
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for certifi==2020.4.5.1
> Best match: certifi 2020.4.5.1
> Adding certifi 2020.4.5.1 to easy-install.pth file
> 
> Using /usr/local/lib/python3.5/dist-packages
> Searching for idna==2.6
> Best match: idna 2.6
> Adding idna 2.6 to easy-install.pth file
> 
> Using /usr/local/lib/python3.5/dist-packages
> Finished processing dependencies for mmdet==0.6.0+unknown
> ```

Something is wrong with your CUDA installation. May be this will [help](https://github.com/open-mmlab/mmdetection/issues/281). 

By the way can you run some other official PyTorch tutorials on your GPU ?

**Comment by Varat7v2** [comment]
Hi [Morteza-j8](https://github.com/Morteza-j8), is it working for you now? I have a small doubt. Is there test images in your ./data/person?
