### ISSUE TITLE
Confidence threshold with which CascadeHRNet evaluated for mAP?

### ISSUE THREAD

**Issue by ishaghodgaonkar** [hasanirtiza/Pedestron#61]
For the Cascade Mask R-CNN model, backbone HRNet, trained on CrowdHuman with an mAP of 84.1, what confidence threshold is used?

Thanks!

**Comment by hasanirtiza** [comment]
Which confidence threshold are you referring to ? Perhaps have a look in the [config file](https://github.com/hasanirtiza/Pedestron/blob/master/configs/elephant/crowdhuman/cascade_hrnet.py) to see some thresholds.
```shell
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.001,
        nms=dict(type='soft_nms', iou_thr=0.5),
        max_per_img=100,
        mask_thr_binary=0.5),
    keep_all_stages=False)
```
Alternatively, have a look at the evaluation protocol of pascal VOC or [have a look here](https://github.com/open-mmlab/mmdetection/issues/474).
