### ISSUE TITLE
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other' in call to _th_and

### ISSUE THREAD

**Issue by uniyushu** [hasanirtiza/Pedestron#62]
**Describe the bug**
I have no problem run demo.py use env below, but when I try training hrnet with crowdhuman, I meet a runtimeerror.Please help me solve this problem

**Reproduction**
1. What command or script did you run?
python tools/train.py configs/elephant/crowdhuman/cascade_hrnet.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I didnt modify any code.
3. What dataset did you use?
crowdhuman

**Environment**
#Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_pytorch_select           0.2                       gpu_0    defaults
addict                    2.2.1                    pypi_0    pypi
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2020.6.24                     0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2020.6.20                py37_0    defaults
cffi                      1.14.0           py37h2e261b9_0    defaults
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.0.130                      0    defaults
cudnn                     7.6.5                cuda10.0_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.17          py37he6710b0_0    defaults
dbus                      1.13.14              hb2f20db_0    defaults
expat                     2.2.6                he6710b0_0    defaults
ffmpeg                    4.0                  hcdf2ecd_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freeglut                  3.0.0                hf484d3e_5    defaults
freetype                  2.9.1                h8a8886c_1    defaults
glib                      2.63.1               h5a9c865_0    defaults
graphite2                 1.3.13               h23475e2_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
h5py                      2.8.0            py37h989c5e5_3    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
hdf5                      1.10.2               hba1933b_1    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.9                      pypi_0    pypi
intel-openmp              2020.0                      166    defaults
jasper                    2.0.14               h07fcdf6_1    defaults
joblib                    0.16.0                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.2.0            py37hfd86e86_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libglu                    9.0.0                hf484d3e_1    defaults
libopencv                 3.4.2                hb342d67_1    defaults
libopus                   1.3.1                h7b6447c_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_0    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libvpx                    1.7.0                h439df22_0    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
matplotlib                3.1.3                    py37_0    defaults
matplotlib-base           3.1.3            py37hef1b27d_0    defaults
mkl                       2020.0                      166    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.0.15           py37ha843d7b_0    defaults
mkl_random                1.1.0            py37hd6b4f25_0    defaults
mmcv                      0.2.14                   pypi_0    pypi
mmdet                     0.6.0+unknown             dev_0    <develop>
ncurses                   6.2                  he6710b0_1    defaults
ninja                     1.9.0            py37hfd86e86_0    defaults
numpy                     1.18.1           py37h4f9e942_0    defaults
numpy-base                1.18.1           py37hde5b4d6_1    defaults
olefile                   0.46                     py37_0    defaults
opencv                    3.4.2            py37h6fd60c2_1    defaults
opencv-python             4.4.0.42                 pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pillow                    7.1.2            py37hb39fc2d_0    defaults
pip                       20.0.2                   py37_3    defaults
pixman                    0.38.0               h7b6447c_0    defaults
prettytable               0.7.2                    pypi_0    pypi
py-opencv                 3.4.2            py37hb342d67_1    defaults
pycocotools               2.0.0                    pypi_0    pypi
pycparser                 2.20                       py_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
python                    3.7.7           hcf32534_0_cpython    defaults
python-dateutil           2.8.1                      py_0    defaults
pytorch                   1.3.1           cuda100py37h53c1284_0    defaults
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1    defaults
readline                  8.0                  h7b6447c_0    defaults
requests                  2.23.0                   pypi_0    pypi
scikit-learn              0.23.1           py37h423224d_0    defaults
scipy                     1.5.0            py37h0b6359f_0    defaults
setuptools                46.1.3                   py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.14.0                   py37_0    defaults
sqlite                    3.31.1               h62c20be_1    defaults
terminaltables            3.1.0                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
torchvision               0.4.2           cuda100py37hecfc37a_0    defaults
tornado                   6.0.4            py37h7b6447c_1    defaults
urllib3                   1.25.9                   pypi_0    pypi
wheel                     0.34.2                   py37_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yapf                      0.30.0                   pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

**Error traceback**
2020-08-20 08:05:19,720 - INFO - workflow: [('train', 1)], max: 240 epochs
/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 94, in main
    logger=logger)
  File "/data/data/ysc_data/project/Pedestron/mmdet/apis/train.py", line 63, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/data/data/ysc_data/project/Pedestron/mmdet/apis/train.py", line 228, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/apis/train.py", line 41, in batch_processor
    losses = model(**data)
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/models/detectors/cascade_rcnn.py", line 137, in forward_train
    *rpn_loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data/data/ysc_data/project/Pedestron/mmdet/models/anchor_heads/rpn_head.py", line 51, in loss
    gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/models/anchor_heads/anchor_head.py", line 179, in loss
    sampling=self.sampling)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/anchor/anchor_target.py", line 108, in anchor_target_single
    cfg.allowed_border)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/anchor/anchor_target.py", line 176, in anchor_inside_flags
    (flat_anchors[:, 2] < img_w + allowed_border) & \
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other' in call to _th_and

**Comment by hasanirtiza** [comment]
It is a well known issue. Please see #17 (scroll down to the bottom)

**Comment by uniyushu** [comment]
Thanks for the response. I fix this by @yuanvq's anwser and mute the Userwarning.I start training with the crowdhuman datasets now.
![image](https://user-images.githubusercontent.com/20262193/90859772-66b8d480-e3bb-11ea-99ee-3b507d5e0ead.png)
![image](https://user-images.githubusercontent.com/20262193/90859693-412bcb00-e3bb-11ea-9f7a-60977c7ffab4.png)

**Comment by SoumiDas** [comment]
Changing line number 173 in mmdet/core/anchor/anchor_target.py

from

inside_flags = valid_flags & \
            (flat_anchors[:, 0] >= -allowed_border) & \
            (flat_anchors[:, 1] >= -allowed_border) & \
            (flat_anchors[:, 2] < img_w + allowed_border) & \
            (flat_anchors[:, 3] < img_h + allowed_border)

to 

inside_flags = valid_flags.bool() & \
            (flat_anchors[:, 0] >= -allowed_border) & \
            (flat_anchors[:, 1] >= -allowed_border) & \
            (flat_anchors[:, 2] < img_w + allowed_border) & \
            (flat_anchors[:, 3] < img_h + allowed_border)

also solves the above issue.

**Comment by yuanvq** [comment]
邮件已收到，祝生活愉快！                                                    袁炜祺
