### ISSUE TITLE
GPU memory leak while training

### ISSUE THREAD

**Issue by uniyushu** [hasanirtiza/Pedestron#63]
**Describe the bug**
I use a docker training Cascade Mask R-CNN with HRNet on Crowdhuman dataset. My GPUs are Tesla V-100(~32480MiB). When I was training,  my GPUs memory keeps growing. It seems when the memory meets the limit. My docker crashed. And report nothing. I have to restart the docker container. 
![image](https://user-images.githubusercontent.com/20262193/91381095-17f6b900-e859-11ea-8887-2e8624ded3b2.png)
![image](https://user-images.githubusercontent.com/20262193/91381138-2c3ab600-e859-11ea-9de9-64d737435cfa.png)
![image](https://user-images.githubusercontent.com/20262193/91381076-0d3c2400-e859-11ea-9457-c7e38cd8a2dd.png)

I know I can use 2 things to continue my training.
1.Reduce batch size to a single img per gpu.
2.resume_from the trained checkpoint in configs.

 Is there anything I can fix the memory leak problem?

**Comment by hasanirtiza** [comment]
This problem should not exist, we have tested it many times on V-100 and DGX machines. My guess is something else is going wrong somewhere, perhaps the way you build the docker-image or CUDA version etc (my guess, not sure). It is hard to comment, why it is crashing, but anyways reduce the batchsize and you should be good to go.

**Comment by uniyushu** [comment]
> This problem should not exist, we have tested it many times on V-100 and DGX machines. My guess is something else is going wrong somewhere, perhaps the way you build the docker-image or CUDA version etc (my guess, not sure). It is hard to comment, why it is crashing, but anyways reduce the batchsize and you should be good to go.

Thanks for the reply. yeah, it is hard to find the bug with nothing to trackback. I also try to find the answer in mmdetection.
If my docker crash again, I will try this solution(https://github.com/open-mmlab/mmdetection/issues/1997).
