### ISSUE TITLE
category_id in unofficial annotations is mean???

### ISSUE THREAD

**Issue by weidalin** [hasanirtiza/Pedestron#73]
hello,In the unofficial annotations (train.json file) you provide, whether "category_id": 1 only refer to the pedestrian label in the official annotations? Other labels such as rider, sitting persons, other persons, group of people, didn't included..........
or "category_id": 1  refer to pedestrians+other persons+...

**Comment by weidalin** [comment]
I'm talking about the CityPerson dataset

**Comment by hasanirtiza** [comment]
`category_id : 1`, Only refers to the pedestrian label. Other labels are not used during training. Have a look [here](https://github.com/hasanirtiza/Pedestron/blob/master/tools/convert_datasets/citypersons/convert_cityperson_to_coco.py) to see how .json file is generated.
