### ISSUE TITLE
Train Model From Scratch

### ISSUE THREAD

**Issue by ChristianLus** [hasanirtiza/Pedestron#75]
Hello, 

I would like to train a model on ECP from scratch for the purpose of testing generalization on other datasets. What would I need to change in the config file in order to do so? I see there is a 'pretrained' field that is filled in by default but I am unfamiliar with the pathing that it is using or what exactly it's loading. I plan on trying out a couple of new settings during training to see how they affect the overall model so I am concerned that any pretrained models will break with new training or architecture changes. 

My other question is in regards to an "unexpected key in source state_dict: incre_modules.0.0.conv1.weight, incre_modules.0.0.bn1.weight, incre_modules.0.0.bn1.bias, ..." I am getting this issue even though I have not changed anything in the config file other than the image size (due to memory limitations). 

I am fairly new to this material so I can provide any additional information that you may need. 

Thank you

**Comment by hasanirtiza** [comment]
What do you mean by changes in the config ? As far as the pre-trained field is concerned, leave it as it is, its simply loading a model pre-trained on imagenet and I would suggest to use this as a starting point. 

`unexpected key in source state_dict: incre_modules.0.0.conv1.weight, incre_modules.0.0.bn1.weight, incre_modules.0.0.bn1.bias, ..."` Is this a warning or an error ? Anyways, this message is telling you that there is some miss match between loaded pre-trained model and the model you defined.
