### ISSUE TITLE
Evaluating Caltech

### ISSUE THREAD

**Issue by ChristianLus** [hasanirtiza/Pedestron#78]
Hello, I am fairly new to deep learning as well as github in general so I apologize if my questions are not clear. 

When I evaluate on Caltech, the output is a a single .json file with detections for 4,024 images. When I go to convert these with the convert to .txt, I was able to run the conversion code only if I called the convert_result(results_jsons) directly rather than using p.map(). 

That being said, it creates a text file for each of the video files (V000.txt-V010.txt, depending on the set). Is this correct, or should the output be different?

When I bring these .txt into matlab, how should I form the hierarchy of these results so that it is able to read everything properly? 

I am experiencing issues where the matlab code cannot find the detections and seems to be wanting a detection file per frame. Am I doing something wrong or am I simply misinterpreting the hierarchy? 

Thank you for your time and I am happy to provide any additional information that may help you or anyone else.

**Comment by hasanirtiza** [comment]
#5

**Comment by ChristianLus** [comment]
Okay so it looks like everything up to the Matlab evaluation code is working for me. Should I place the Pedestron_Result/ folder next to the ResultsEval folder when I bring them into Matlab? I suppose don't quite understand where the evaluation code is trying to look for the detection results. 

Thank you again for your quick response.

**Comment by hasanirtiza** [comment]
Did you follow the instructions in [this file](https://github.com/hasanirtiza/Pedestron/blob/master/Datasets-PreProcessing.md) particularly for `Caltech` point 4 and 5 ?

**Comment by ChristianLus** [comment]
I followed them as well as I could. I will give it another try and let you know if it is able to run the files. I apologize for any confusion.

**Comment by hasanirtiza** [comment]
Just see how the Matlab code is expecting your paths to be, its most definitely a path issue.

**Comment by ChristianLus** [comment]
Hello, I wanted to let you know that I was able to figure it out. I'm not sure what I was doing wrong at first but now the evaluation code is running just fine. Thank you for your help!
