### ISSUE TITLE
How to convert Caltech to COCO

### ISSUE THREAD

**Issue by zl9501** [hasanirtiza/Pedestron#79]
Hi, thanks for your nice repo! Now I have some data in Caltech format, I'd like to train them using Pedestron, how to convert them to COCO format?

**Comment by hasanirtiza** [comment]
Currently, we do not have the conversion script in the repo. You can have a look at conversion scripts of other datasets in `tools/covert_datasets` and see how they are converted to COCO format. Or may some thing on the internet [like](https://github.com/mitmul/caltech-pedestrian-dataset-converter) this might help.

**Comment by zl9501** [comment]
Thanks a lot for your kind reply!
