### ISSUE TITLE
Benchmarking of pre-trained models on pedestrian detection datasets

### ISSUE THREAD

**Issue by zgsxwsdxg** [hasanirtiza/Pedestron#82]
Hello，Reasonable and Heavy is for what indicator？these indicator is representative for what meanings？ which case is is good performance？ths.

**Comment by hasanirtiza** [comment]
`Reasonable` means little to no occlusion, `Heavy` corresponds to heavily occluded pedestrian. For exact definition, refer to Table 2 of our [paper](https://arxiv.org/pdf/2003.08799.pdf).
