### ISSUE TITLE
 a slightly better implementation of CSP - CVPR 2019 to Pedestron along with a pre-trained model

### ISSUE THREAD

**Issue by zgsxwsdxg** [hasanirtiza/Pedestron#83]
Hello, where is the slightly better implementation of CSP - CVPR 2019 to Pedestron along with a pre-trained model?
 Thx.

**Comment by hasanirtiza** [comment]
> Hello, where is the slightly better implementation of CSP - CVPR 2019 to Pedestron along with a pre-trained model?

Inside this repo, did you bother exploring the repo ?
