### ISSUE TITLE
The reasonable subset gt

### ISSUE THREAD

**Issue by fyture** [hasanirtiza/Pedestron#84]
Hi，The same result evaluated by your Reasonable-mat is different from the Reasonable-mat that CSP offered. What did I miss? Thanks

**Comment by hasanirtiza** [comment]
Which model did you evaluate ? How much is the discrepancy ?

**Comment by fyture** [comment]
> Which model did you evaluate ? How much is the discrepancy ?

About Caltech , my own model evaluated by CSP reasonable gt is 13 while using your reasonable gt is 11. And also the size of these two gt files are different. So I don't know what I miss. By the  way, where could I get these different subset gt files. I'm a beginner in this field.Appreciate your wonderful work!

**Comment by hasanirtiza** [comment]
I did not find any difference in sizes for CSP reasonable mat and Pedestron's reasonable mat, both have outer dimensions 1x4024 and also inside each cell, the dimensions are exactly the same. Could you double check, if you are doing everything correctly. 

Secondly, you do not need any `gt file`, you can generate `gt files` directly from the code by yourself.
Download the new annotations for caltech from [here](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/people-detection-pose-estimation-and-tracking/how-far-are-we-from-solving-pedestrian-detection).

Uncomment line 30 in [dbEval.m](https://github.com/hasanirtiza/Pedestron/blob/master/tools/caltech/eval_caltech/dbEval.m), provide the path variable (`pth.annDir=['my folder/anno_test_1xnew'];`) to the txt annotations for the testing set, the code will generate the `gt file`. 
 Alternatively, have look here as well #5, on how to generate for other settings.

**Comment by fyture** [comment]
> I did not find any difference in sizes for CSP reasonable mat and Pedestron's reasonable mat, both have outer dimensions 1x4024 and also inside each cell, the dimensions and are exactly the same. Could you double check, if you are doing everything correctly.
> 
> Secondly, you do not need any `gt file`, you can generate `gt files` directly from the code by yourself.
> Download the new annotations for caltech from [here](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/people-detection-pose-estimation-and-tracking/how-far-are-we-from-solving-pedestrian-detection).
> 
> Uncomment line 30 in [dbEval.m](https://github.com/hasanirtiza/Pedestron/blob/master/tools/caltech/eval_caltech/dbEval.m), provide the path(variable `pth.annDir=['my folder/anno_test_1xnew'];`) to the txt annotations for the testing set, the code will generate the `gt file`.
> Alternatively, have look here as well #5, on how to generate for other settings.

Thank you so much!!!!

**Comment by fyture** [comment]
> > I did not find any difference in sizes for CSP reasonable mat and Pedestron's reasonable mat, both have outer dimensions 1x4024 and also inside each cell, the dimensions and are exactly the same. Could you double check, if you are doing everything correctly.
> > Secondly, you do not need any `gt file`, you can generate `gt files` directly from the code by yourself.
> > Download the new annotations for caltech from [here](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/people-detection-pose-estimation-and-tracking/how-far-are-we-from-solving-pedestrian-detection).
> > Uncomment line 30 in [dbEval.m](https://github.com/hasanirtiza/Pedestron/blob/master/tools/caltech/eval_caltech/dbEval.m), provide the path(variable `pth.annDir=['my folder/anno_test_1xnew'];`) to the txt annotations for the testing set, the code will generate the `gt file`.
> > Alternatively, have look here as well #5, on how to generate for other settings.
> 
> Thank you so much!!!!

Really sorry for bothering you again. I followed your guide and successfully got the reasults of Reasonable, Heavy and All subsets. But other than these three subsets, The reasults of other subsets, say Scale=large, is NAN. What went wrong? Don‘t the new annotations support other subets or some other reasons? Thanks again!!!!!!!!!!

**Comment by hasanirtiza** [comment]
Hard to comment that why exactly are you getting NaN. First check if there are any samples in the ground-truth file belonging to `Scale=Large`. Play with the visibility parameter, which is by default set to `[inf inf]`, may be start by setting it to `[0.65 inf]`.
