### ISSUE TITLE
an issue about crowdhuman annotation

### ISSUE THREAD

**Issue by jacktkk** [hasanirtiza/Pedestron#85]
Do you consider full/visible properties in the original labels when generating train/val.json files? 
Or could you please share the code that makes train/val.json files?
I'm looking forward to your reply!

**Comment by hasanirtiza** [comment]
We used only full body bounding box.
Have a look at the [conversions scripts](https://github.com/hasanirtiza/Pedestron/tree/master/tools/convert_datasets) to see how to generate annotations file.

**Comment by jacktkk** [comment]
okay, thanks for your reply!
