### ISSUE TITLE
What about the performance of vgg16 based Faster-RCNN?

### ISSUE THREAD

**Issue by Jokoe66** [hasanirtiza/Pedestron#9]
Grateful to open-sourcing such a convenient PedDet toolbox. I have tried training Adapted Faster-RCNN (vgg16 based, as described in the CityPersons paper) on CityPersons dataset before, with the official mmdetection repo., where I get a log average miss rate(MR) of ~16%. However, the reported MR in the CityPersons paper is ~15%. So have you trained vgg16 based Faster-RCNN and if yes, how about the evaluation result?

**Comment by hasanirtiza** [comment]
I do not exactly remember the performance of Faster R-CNN with vgg16. However, we do provide configurations with HRNet for Faster R-CNN (pre-trained model as well), perhaps you can give a shot with the same configurations (training-time augmentation etc.) using vgg16. By the way, MGAN uses VGG16 and we have ported the code and pre-trained model in Pedestron, but unfortunately at the moment its test only.
We will at some point in future add Faster R-CNN with vgg16.

**Comment by PhatHSRW** [comment]
> Grateful to open-sourcing such a convenient PedDet toolbox. I have tried training Adapted Faster-RCNN (vgg16 based, as described in the CityPersons paper) on CityPersons dataset before, with the official mmdetection repo., where I get a log average miss rate(MR) of ~16%. However, the reported MR in the CityPersons paper is ~15%. So have you trained vgg16 based Faster-RCNN and if yes, how about the evaluation result?

Hi, can you share me the config of your VGG backbone?
