### ISSUE TITLE
Question about new annotation

### ISSUE THREAD

**Issue by AstrayChao** [hasanirtiza/Pedestron#90]
Hi, 

According to #5, I download the new annotation from [url](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/people-detection-pose-estimation-and-tracking/how-far-are-we-from-solving-pedestrian-detection/), but it's 1x annotation rather than 10x, how can I get the new 10x annotations? 
 
thanks!

**Comment by hasanirtiza** [comment]
On the [url](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/people-detection-pose-estimation-and-tracking/how-far-are-we-from-solving-pedestrian-detection/), if you scroll down it says `Caltech 10x original annotations aligned `, did you try that ?

**Comment by AstrayChao** [comment]
> On the [url](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/people-detection-pose-estimation-and-tracking/how-far-are-we-from-solving-pedestrian-detection/), if you scroll down it says `Caltech 10x original annotations aligned `, did you try that ?

thanks for your reply, I also downloaded that, but there's something different between `Caltech 10x original annotations aligned` and `new annotations 1x`, e.g.  there's no such visible bbox annotation for `Caltech 10x original annotations aligned`, and I need visible bbox in my model.
