### ISSUE TITLE
from .. import deform_conv_cuda ImportError: cannot import name 'deform_conv_cuda'

### ISSUE THREAD

**Issue by ayennam** [hasanirtiza/Pedestron#92]
**Environment**
 - OS: [e.g., Ubuntu 16.04.6] ubuntu 18.04
 - GCC [e.g., 5.4.0] 7
 - PyTorch version [e.g., 1.1.0] pip 1.4
- How you installed PyTorch [e.g., pip, conda, source] pip
- GPU model [e.g., 1080Ti, V100]  2080tu
- CUDA and CUDNN version 10.1 and  7.6

```

**Comment by hasanirtiza** [comment]
Did you install the Pedestron correctly ? Moreover, did you follow the instructions in the [installation file](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) ?

**Comment by ayennam** [comment]
used colab and its working but on local needs to be share docker to setup clean environement

**Comment by hasanirtiza** [comment]
To me it the error you have posted seems to be related to incorrect installation than related to docker. Nonetheless, I am closing this issue, feel free to reopen.
