### ISSUE TITLE
how to eval or test pascle voc format data?

### ISSUE THREAD

**Issue by ayennam** [hasanirtiza/Pedestron#93]
I have data in pascal VOC format and need to test my data with this pre-trained model, just for evaluation or test to get mAP values?

**Comment by hasanirtiza** [comment]
I am not 100% sure, but did you try running `python tool/test.py` command and changing dataset type in configs to `voc`. Else a straight forward way is that you convert your dataset to coco, you should find plenty of scripts on the net - which convert `voc2coco`. Subsequently, running this should get you mAP.
`python ./tools/test.py configs/elephant/CONFIG_FILE ./MODEL_FILE.pth.stu --out CrowdHuman12.pkl --eval bbox
`

**Comment by ayennam** [comment]
@hasanirtiza 
my cmd
%%shell
cd /content/Pedestron/
pwd
conda run python tools/test.py configs/elephant/crowdhuman/cascade_hrnet.py models_pretrained/epoch_19.pth.stu --out CrowdHuman12.pkl --eval bbox

in google coalb

ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['python', 'tools/test.py', 'configs/elephant/crowdhuman/cascade_hrnet.py', 'models_pretrained/epoch_19.pth.stu', '--out', 'CrowdHuman12.pkl', '--eval', 'bbox']' command failed.  (See above for error)
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!

Traceback (most recent call last):
  File "tools/test.py", line 205, in <module>
    main()
  File "tools/test.py", line 165, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 172, in load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

---------------------------------------------------------------------------

CalledProcessError                        Traceback (most recent call last)

<ipython-input-38-c888477e4cbf> in <module>()
----> 1 get_ipython().run_cell_magic('shell', '', 'cd /content/Pedestron/\npwd\nconda run python tools/test.py configs/elephant/crowdhuman/cascade_hrnet.py models_pretrained/epoch_19.pth.stu --out CrowdHuman12.pkl --eval bbox')

2 frames

/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py in check_returncode(self)
    137     if self.returncode:
    138       raise subprocess.CalledProcessError(
--> 139           returncode=self.returncode, cmd=self.args, output=self.output)
    140 
    141   def _repr_pretty_(self, p, cycle):  # pylint:disable=unused-argument

CalledProcessError: Command 'cd /content/Pedestron/
pwd
conda run python tools/test.py configs/elephant/crowdhuman/cascade_hrnet.py models_pretrained/epoch_19.pth.stu --out CrowdHuman12.pkl --eval bbox' returned non-zero exit status 1.

**Comment by ayennam** [comment]
now

@hasanirtiza 

ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['python', '/content/Pedestron/tools/test.py', '/content/Pedestron/configs/elephant/crowdhuman/cascade_hrnet.py', '/content/Pedestron/models_pretrained/epoch_19.pth.stu', '--out', '/content/Pedestron/CrowdHuman12.pkl', '--eval', 'bbox']' command failed.  (See above for error)
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!

Traceback (most recent call last):
  File "/content/Pedestron/tools/test.py", line 205, in <module>
    main()
  File "/content/Pedestron/tools/test.py", line 165, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 172, in load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

---------------------------------------------------------------------------

CalledProcessError                        Traceback (most recent call last)

<ipython-input-46-1893905eb0ce> in <module>()
----> 1 get_ipython().run_cell_magic('shell', '', '#cd /content/Pedestron/\n#pwd\nconda run python /content/Pedestron/tools/test.py /content/Pedestron/configs/elephant/crowdhuman/cascade_hrnet.py /content/Pedestron/models_pretrained/epoch_19.pth.stu --out /content/Pedestron/CrowdHuman12.pkl --eval bbox')

2 frames

/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py in check_returncode(self)
    137     if self.returncode:
    138       raise subprocess.CalledProcessError(
--> 139           returncode=self.returncode, cmd=self.args, output=self.output)
    140 
    141   def _repr_pretty_(self, p, cycle):  # pylint:disable=unused-argument

CalledProcessError: Command '#cd /content/Pedestron/
#pwd
conda run python /content/Pedestron/tools/test.py /content/Pedestron/configs/elephant/crowdhuman/cascade_hrnet.py /content/Pedestron/models_pretrained/epoch_19.pth.stu --out /content/Pedestron/CrowdHuman12.pkl --eval bbox' returned non-zero exit status 1.
