### ISSUE TITLE
About the experiment results on Crowdhuman with CSP

### ISSUE THREAD

**Issue by hh23333** [hasanirtiza/Pedestron#94]
Hi, thanks for sharing your excellent work! I trained CSP on crowdhuman dataset with almost the same setting as training it on cityperson, but got an unsatisfying results, (about 72AP50, and 70MR-2). Have you carried out an experiment on CrowdHuman with CSP? Could you give me some suggestions? Thanks

**Comment by hasanirtiza** [comment]
It is a known problem with CSP, since it relies on fixed-aspect ratio (0.41) and center line annotation, it suffers a degrade in performance whenever the annotation is not fixed and/or center-line. Personally, we have also experienced low CSP performance on `crowdhuman`.

**Comment by hh23333** [comment]
Got it! I used the pred_width operation to solve the problem of fixed aspect ratio, but still got poor results. Anyway, thanks for you reply.
