### ISSUE TITLE
command failed?

### ISSUE THREAD

**Issue by ayennam** [hasanirtiza/Pedestron#95]
now

@hasanirtiza

ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['python', '/content/Pedestron/tools/test.py', '/content/Pedestron/configs/elephant/crowdhuman/cascade_hrnet.py', '/content/Pedestron/models_pretrained/epoch_19.pth.stu', '--out', '/content/Pedestron/CrowdHuman12.pkl', '--eval', 'bbox']' command failed. (See above for error)
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!

Traceback (most recent call last):
File "/content/Pedestron/tools/test.py", line 205, in
main()
File "/content/Pedestron/tools/test.py", line 165, in main
checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
File "/usr/local/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 172, in load_checkpoint
checkpoint = torch.load(filename, map_location=map_location)
File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
return _load(f, map_location, pickle_module, **pickle_load_args)
File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 563, in _load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

CalledProcessError Traceback (most recent call last)

in ()
----> 1 get_ipython().run_cell_magic('shell', '', '#cd /content/Pedestron/\n#pwd\nconda run python /content/Pedestron/tools/test.py /content/Pedestron/configs/elephant/crowdhuman/cascade_hrnet.py /content/Pedestron/models_pretrained/epoch_19.pth.stu --out /content/Pedestron/CrowdHuman12.pkl --eval bbox')

2 frames

/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py in check_returncode(self)
137 if self.returncode:
138 raise subprocess.CalledProcessError(
--> 139 returncode=self.returncode, cmd=self.args, output=self.output)
140
141 def repr_pretty(self, p, cycle): # pylint:disable=unused-argument

CalledProcessError: Command '#cd /content/Pedestron/
#pwd
conda run python /content/Pedestron/tools/test.py /content/Pedestron/configs/elephant/crowdhuman/cascade_hrnet.py /content/Pedestron/models_pretrained/epoch_19.pth.stu --out /content/Pedestron/CrowdHuman12.pkl --eval bbox' returned non-zero exit status 1.

**Comment by hasanirtiza** [comment]
`python tools/test.py ./configs/elephant/crowdhuman/cascade_hrnet.py ./models_pretrained/epoch_8.pth.stu --eval bbox`


This command works fine on my machine, could you simply copy paste this.
