### ISSUE TITLE
Error when training on Wider Pedestrian Dataset

### ISSUE THREAD

**Issue by SamihaSara** [hasanirtiza/Pedestron#99]
I ran the following command to train on single GPU from scratch
**python tools/train.py /home/samiha/Pedestron/configs/elephant/wider_pedestrain/cascade_hrnet.py**
But its showing the following error.
**OSError: /home/jl2/code/irtiza/mmdetection/jobs/wider_challenge/cascade_hrnet/work_dirs/cityperson_cascade_rcnn_hrnetv2p_w32/epoch_9.pth is not a checkpoint file**

Does training on Wider Pedestrian require any pretrained model? Please suggest any idea to solve this problem.
Attached is the error message I am getting.
![Screenshot from 2021-05-17 23-36-01](https://user-images.githubusercontent.com/9627710/118497793-bec51180-b768-11eb-8c00-2edf48b21efe.png)

**Comment by hasanirtiza** [comment]
In the config file, on line 286 set `resume_from = None`. Or pull the repo again, I have updated the line.

**Comment by SamihaSara** [comment]
@hasanirtiza Many Thanks this was helpful, but for single Ram, I got an out of RAM memory error. So I tried with 4 GPUs to train using the following command:
**./tools/dist_train.sh configs/elephant/wider_pedestrain/cascade_hrnet.py 4**

I have modified config to **imgs_per_gpu=1,workers_per_gpu=1**, img_scale=(960, 512), warmup_ratio=1.0 / 5,
and epoch = 2

But unfortunately facing **subprocess.CalledProcessError**(details are in the attached picture). Please advise ideas to solve this issue.

![Screenshot from 2021-05-18 22-47-13](https://user-images.githubusercontent.com/9627710/118653652-1c219700-b82b-11eb-85c1-aee5bef04bf7.png)
![Screenshot from 2021-05-18 22-47-19](https://user-images.githubusercontent.com/9627710/118653672-1fb51e00-b82b-11eb-9ff5-f2dc4145b6ac.png)
![Screenshot from 2021-05-18 22-47-40](https://user-images.githubusercontent.com/9627710/118653686-217ee180-b82b-11eb-874b-cc258322a569.png)

**Comment by hasanirtiza** [comment]
Does not appear to be a RAM issue, have a look at #17 (scroll at the end). Also before posting another comment, have a look at previous issues by searching some keywords.

**Comment by SamihaSara** [comment]
Sorry I am facing another issue. I have checked previous GitHUb issues, similar problem could not find. 
When I am executing 
**./tools/dist_train.sh configs/elephant/wider_pedestrain/cascade_hrnet.py 4**
I am just seeing this warning  **"UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead."**, and the command ends. Training on the dataset does not start and the process finishes with this warning.
Is this because of package incompatibility? Please suggest any solution.

![Screenshot from 2021-05-21 04-59-35](https://user-images.githubusercontent.com/9627710/119034687-f4306000-b9f1-11eb-9d71-121d29446e65.png)
